graph TD
    % Entities in blue
    EntityA{{#0000ff}} --> AttributeA{{white}}
    EntityA{{#0000ff}} --> AttributeB{{white}}

    % Attributes connected to their entities
    EntityB{{#0000ff}} --> AttributeC{{white}}
    EntityB{{#0000ff}} --> AttributeD{{white}}

    % Relations between entities in orange
    Relation1{{#ffa500}} --> EntityA
    Relation2{{#ffa500}} --> EntityB

    % Goals connected to relevant nodes in green
    Goal1{{#008000}} --> EntityA
    Goal1{{#008000}} --> AttributeC

    % Conditions connected to relevant nodes in red
    Condition1{{#ff0000}} --> AttributeB
    Condition2{{#ff0000}} --> AttributeD

    % Decision Variables connected to relevant entities in purple
    DecisionVar1{{#800080}} --> EntityA
    DecisionVar2{{#800080}} --> EntityB