graph TD
    %% =============== STYLING ===============
    classDef entity fill:#1f77b4,stroke:#000,color:white,font-weight:bold;
    classDef attribute fill:#ffffff,stroke:#333,stroke-width:1px,color:#000;
    classDef relation fill:#ff8c00,stroke:#000,color:white,font-weight:bold;
    classDef goal fill:#2ca02c,stroke:#000,color:white,font-weight:bold;
    classDef condition fill:#d62728,stroke:#000,color:white,font-weight:bold;
    classDef decisionvar fill:#9467bd,stroke:#000,color:white,font-weight:bold;

    %% =============== ENTITIES (Blue) ===============
    E0[Project]:::entity
    E1[Team]:::entity
    E2[Worker]:::entity
    E3[Feature]:::entity
    E4[Skill]:::entity
    E5[Role]:::entity
    E6[ProductOwner]:::entity
    E7[ScrumMaster]:::entity
    E8[ProductBacklog]:::entity
    E9[Sprint]:::entity
    E10[SprintPlanning]:::entity
    E11[DailyScrum]:::entity
    E12[SprintReview]:::entity
    E13[SprintRetrospective]:::entity
    E14[SprintBacklog]:::entity
    E15[SprintGoal]:::entity
    E16[Epic]:::entity
    E17[UserStory]:::entity
    E18[Task]:::entity
    E19[DevelopmentSnapshot]:::entity
    E20[Blocker]:::entity
    E21[Stakeholder]:::entity
    E22[Velocity]:::entity
    E23[ReleasePlan]:::entity
    E24[Roadmap]:::entity
    E25[ScrumBoard]:::entity
    E26[FeatureDocumentation]:::entity

    %% =============== ATTRIBUTES (White) ===============
    A00[id]:::attribute
    A01[name]:::attribute
    A02[project_start]:::attribute
    A03[project_end]:::attribute
    A04[description]:::attribute
    A05[budget]:::attribute
    A06[status]:::attribute
    A07[target_audience]:::attribute
    A08[priority]:::attribute

    A10[id]:::attribute
    A11[name]:::attribute
    A12[team_size]:::attribute
    A13[team_start]:::attribute
    A14[team_status]:::attribute
    A15[location]:::attribute
    A16[team_type]:::attribute

    A20[id]:::attribute
    A21[name]:::attribute
    A22[first_name]:::attribute
    A23[email]:::attribute
    A24[start_date]:::attribute
    A25[status]:::attribute
    A26[availability]:::attribute

    A30[id]:::attribute
    A31[title]:::attribute
    A32[description]:::attribute
    A33[status]:::attribute
    A34[priority]:::attribute
    A35[estimated_effort]:::attribute

    A40[id]:::attribute
    A41[label]:::attribute
    A42[description]:::attribute
    A43[level]:::attribute
    A44[certified]:::attribute
    A45[category]:::attribute

    A50[id]:::attribute
    A51[role_name]:::attribute
    A52[description]:::attribute
    A53[area_of_responsibility]:::attribute

    A60[id]:::attribute
    A61[name]:::attribute
    A62[email]:::attribute
    A63[availability]:::attribute

    A70[id]:::attribute
    A71[name]:::attribute
    A72[email]:::attribute
    A73[experience]:::attribute

    A80[id]:::attribute
    A81[created_on]:::attribute
    A82[last_updated]:::attribute
    A83[number_of_entries]:::attribute
    A84[status]:::attribute

    A90[id]:::attribute
    A91[sprint_number]:::attribute
    A92[start_date]:::attribute
    A93[end_date]:::attribute
    A94[status]:::attribute
    A95[achievement_of_goal]:::attribute

    A100[id]:::attribute
    A101[date]:::attribute
    A102[duration_(min)]:::attribute
    A103[moderation]:::attribute
    A104[outcome_documentation]:::attribute

    A110[id]:::attribute
    A111[date]:::attribute
    A112[time]:::attribute
    A113[duration]:::attribute
    A114[moderation]:::attribute

    A120[id]:::attribute
    A121[date]:::attribute
    A122[duration]:::attribute
    A123[feedback_documentation]:::attribute
    A124[attendees_count]:::attribute

    A130[id]:::attribute
    A131[date]:::attribute
    A132[duration]:::attribute
    A133[improvement_actions]:::attribute
    A134[team_satisfaction]:::attribute
    A135[moderation]:::attribute

    A140[id]:::attribute
    A141[number_of_tasks]:::attribute
    A142[last_updated]:::attribute
    A143[status]:::attribute
    A144[total_effort]:::attribute

    A150[id]:::attribute
    A151[objective_description]:::attribute
    A152[achievement_status]:::attribute
    A153[benefit]:::attribute

    A160[id]:::attribute
    A161[title]:::attribute
    A162[description]:::attribute
    A163[priority]:::attribute
    A164[status]:::attribute
    A165[estimated_effort]:::attribute

    A170[id]:::attribute
    A171[title]:::attribute
    A172[description]:::attribute
    A173[acceptance_criteria]:::attribute
    A174[priority]:::attribute
    A175[story_points]:::attribute
    A176[status]:::attribute

    A180[id]:::attribute
    A181[title]:::attribute
    A182[description]:::attribute
    A183[status]:::attribute
    A184[effort]:::attribute
    A185[type]:::attribute

    A190[id]:::attribute
    A191[version_number]:::attribute
    A192[creation_date]:::attribute
    A193[test_status]:::attribute
    A194[deployment_target]:::attribute
    A195[documentation]:::attribute

    A200[id]:::attribute
    A201[title]:::attribute
    A202[description]:::attribute
    A203[severity]:::attribute
    A204[status]:::attribute
    A205[detected_on]:::attribute
    A206[resolved_on]:::attribute

    A210[id]:::attribute
    A211[name]:::attribute
    A212[organization]:::attribute
    A213[role]:::attribute
    A214[email]:::attribute
    A215[area_of_interest]:::attribute
    A216[influence_level]:::attribute
    A217[relevance_to_feature]:::attribute

    A220[id]:::attribute
    A221[number_of_sprints_used]:::attribute
    A222[avg._story_points]:::attribute
    A223[max_velocity]:::attribute
    A224[min_velocity]:::attribute
    A225[trend]:::attribute

    A230[id]:::attribute
    A231[version]:::attribute
    A232[planned_date]:::attribute
    A233[included_features]:::attribute
    A234[status]:::attribute

    A240[id]:::attribute
    A241[start_date]:::attribute
    A242[end_date]:::attribute
    A243[milestones]:::attribute
    A244[objectives]:::attribute
    A245[versions]:::attribute

    A250[id]:::attribute
    A251[board_type]:::attribute
    A252[columns_(todo/done...)]:::attribute
    A253[number_of_cards]:::attribute
    A254[last_updated]:::attribute

    A260[id]:::attribute
    A261[title]:::attribute
    A262[description]:::attribute
    A263[creation_date]:::attribute
    A264[change_log]:::attribute
    A265[linked_requirements]:::attribute
    A266[author]:::attribute

    %% =============== RELATIONS (Orange) ===============
    R1[is_assigned_to_project]:::relation
    R2[belongs_to_team]:::relation
    R3[has_skill]:::relation
    R4[takes_on_role]:::relation
    R5[manages_backlog]:::relation
    R6[is_supported_by]:::relation
    R7[contains_feature]:::relation
    R8[contains_epic]:::relation
    R9[contains_user_story]:::relation
    R10[consists_of_tasks]:::relation
    R11[is_in_sprint_backlog]:::relation
    R12[belongs_to_sprint]:::relation
    R13[pursues_goal]:::relation
    R14[contains_tasks]:::relation
    R15[documents_feature]:::relation
    R16[is_blocked_by]:::relation
    R17[participates_in]:::relation
    R18[moderates_retrospective]:::relation
    R19[refers_to_team]:::relation
    R20[plans_release]:::relation
    R21[is_part_of_roadmap]:::relation
    R22[generates_snapshot]:::relation

    %% =============== GOALS (Green) ===============
    G0[maximize_project_budget]:::goal
    G1[maximize_team_size]:::goal
    G2[maximize_worker_availability]:::goal
    G3[minimize_feature_estimated_effort]:::goal
    G4[maximize_user_story_story_points]:::goal
    G5[minimize_sprint_duration]:::goal
    G6[maximize_sprint_achievement_of_goal]:::goal
    G7[minimize_blocker_severity]:::goal
    G8[maximize_velocity_avg_story_points]:::goal
    G9[minimize_task_effort]:::goal
    G10[maximize_sprint_review_attendees]:::goal
    G11[minimize_sprint_planning_duration]:::goal
    G12[maximize_team_satisfaction]:::goal
    G13[minimize_release_plan_delay]:::goal
    G14[maximize_number_of_features_released]:::goal

    %% =============== CONDITIONS (Red) ===============
    C0[require_project_status_active]:::condition
    C1[require_team_status_active]:::condition
    C2[require_worker_status_active]:::condition
    C3[require_feature_status_not_done]:::condition
    C4[require_user_story_status_todo]:::condition
    C5[require_task_status_not_blocked]:::condition
    C6[require_blocker_status_resolved]:::condition
    C7[require_sprint_status_active]:::condition
    C8[require_sprint_goal_achievement_pending]:::condition
    C9[require_skill_certified]:::condition
    C10[require_role_area_defined]:::condition
    C11[require_product_backlog_status_open]:::condition
    C12[require_velocity_trend_positive]:::condition
    C13[require_release_plan_status_active]:::condition
    C14[require_roadmap_milestones_defined]:::condition

    %% =============== DECISION VARIABLES (Purple) ===============
    DV0[project_priority_assignment]:::decisionvar
    DV1[team_assignment_weight]:::decisionvar
    DV2[worker_availability_score]:::decisionvar
    DV3[feature_priority]:::decisionvar
    DV4[user_story_priority]:::decisionvar
    DV5[task_effort_estimate]:::decisionvar
    DV6[sprint_duration_days]:::decisionvar
    DV7[planning_meeting_duration]:::decisionvar
    DV8[daily_scrum_duration]:::decisionvar
    DV9[retrospective_moderation_score]:::decisionvar
    DV10[blocker_severity_level]:::decisionvar
    DV11[velocity_calculation_window]:::decisionvar
    DV12[release_version_number]:::decisionvar
    DV13[roadmap_start_year]:::decisionvar
    DV14[documentation_completion_status]:::decisionvar

    %% =============== ENTITY -> ATTRIBUTE CONNECTIONS ===============
    E0 --> A00 & A01 & A02 & A03 & A04 & A05 & A06 & A07 & A08
    E1 --> A10 & A11 & A12 & A13 & A14 & A15 & A16
    E2 --> A20 & A21 & A22 & A23 & A24 & A25 & A26
    E3 --> A30 & A31 & A32 & A33 & A34 & A35
    E4 --> A40 & A41 & A42 & A43 & A44 & A45
    E5 --> A50 & A51 & A52 & A53
    E6 --> A60 & A61 & A62 & A63
    E7 --> A70 & A71 & A72 & A73
    E8 --> A80 & A81 & A82 & A83 & A84
    E9 --> A90 & A91 & A92 & A93 & A94 & A95
    E10 --> A100 & A101 & A102 & A103 & A104
    E11 --> A110 & A111 & A112 & A113 & A114
    E12 --> A120 & A121 & A122 & A123 & A124
    E13 --> A130 & A131 & A132 & A133 & A134 & A135
    E14 --> A140 & A141 & A142 & A143 & A144
    E15 --> A150 & A151 & A152 & A153
    E16 --> A160 & A161 & A162 & A163 & A164 & A165
    E17 --> A170 & A171 & A172 & A173 & A174 & A175 & A176
    E18 --> A180 & A181 & A182 & A183 & A184 & A185
    E19 --> A190 & A191 & A192 & A193 & A194 & A195
    E20 --> A200 & A201 & A202 & A203 & A204 & A205 & A206
    E21 --> A210 & A211 & A212 & A213 & A214 & A215 & A216 & A217
    E22 --> A220 & A221 & A222 & A223 & A224 & A225
    E23 --> A230 & A231 & A232 & A233 & A234
    E24 --> A240 & A241 & A242 & A243 & A244 & A245
    E25 --> A250 & A251 & A252 & A253 & A254
    E26 --> A260 & A261 & A262 & A263 & A264 & A265 & A266

    %% =============== RELATION CONNECTIONS ===============
    E1 --> R1 --> E0
    E2 --> R2 --> E1
    E2 --> R3 --> E4
    E2 --> R4 --> E5
    E6 --> R5 --> E8
    E1 --> R6 --> E7
    E8 --> R7 --> E3
    E8 --> R8 --> E16
    E16 --> R9 --> E17
    E17 --> R10 --> E18
    E17 --> R11 --> E14
    E14 --> R12 --> E9
    E9 --> R13 --> E15
    E25 --> R14 --> E18
    E26 --> R15 --> E3
    E18 --> R16 --> E20
    E21 --> R17 --> E12
    E7 --> R18 --> E13
    E22 --> R19 --> E1
    E23 --> R20 --> E3
    E23 --> R21 --> E24
    E9 --> R22 --> E19

    %% =============== GOAL CONNECTIONS (to Entity/Attribute) ===============
    G0 --> A05 & E0
    G1 --> A12 & E1
    G2 --> A26 & E2
    G3 --> A35 & E3
    G4 --> A175 & E17
    G5 --> A93 & A92 & E9
    G6 --> A95 & E9
    G7 --> A203 & E20
    G8 --> A222 & E22
    G9 --> A184 & E18
    G10 --> A124 & E12
    G11 --> A102 & E10
    G12 --> A134 & E13
    G13 --> A232 & E23
    G14 --> A233 & E23

    %% =============== CONDITION CONNECTIONS ===============
    C0 --> A06 & E0
    C1 --> A14 & E1
    C2 --> A25 & E2
    C3 --> A33 & E3
    C4 --> A176 & E17
    C5 --> A183 & E18
    C6 --> A204 & E20
    C7 --> A94 & E9
    C8 --> A152 & E15
    C9 --> A44 & E4
    C10 --> A53 & E5
    C11 --> A84 & E8
    C12 --> A225 & E22
    C13 --> A234 & E23
    C14 --> A243 & E24

    %% =============== DECISION VARIABLE CONNECTIONS ===============
    DV0 --> E0 & A08
    DV1 --> E1 & A12
    DV2 --> E2 & A26
    DV3 --> E3 & A34
    DV4 --> E17 & A174
    DV5 --> E18 & A184
    DV6 --> E9 & A92 & A93
    DV7 --> E10 & A102
    DV8 --> E11 & A113
    DV9 --> E13 & A135
    DV10 --> E20 & A203
    DV11 --> E22 & A221
    DV12 --> E23 & A231
    DV13 --> E24 & A241
    DV14 --> E26 & A264

    %% =============== OPTIONAL: Improve Layout with Invisible Nodes (if needed) ===============
    %% Add subgraphs or positioning hints if layout is too tangled in viewer