graph TD
    style entity fill:#0000FF,stroke:#0000FF
    style attribute fill:#FFFFFF,stroke:#000000
    style relation fill:#FFA500,stroke:#FFA500
    style goal fill:#00FF00,stroke:#00FF00
    style condition fill:#FF0000,stroke:#FF0000
    style decision fill:#800080,stroke:#800080

    %% Entities
    Entity1[Entity1] style entity
    Entity2[Entity2] style entity
    Entity3[Entity3] style entity

    %% Attributes
    Entity1 --> Attribute1(Attr1) style attribute
    Entity1 --> Attribute2(Attr2) style attribute
    Entity2 --> Attribute3(Attr3) style attribute
    Entity3 --> Attribute4(Attr4) style attribute

    %% Relations
    Entity1 --> Relation1(Rel1) style relation
    Entity2 --> Relation2(Rel2) style relation
    Entity3 --> Relation3(Rel3) style relation

    %% Goals
    Entity1 --> Goal1(Goal1) style goal
    Entity2 --> Goal2(Goal2) style goal
    Entity3 --> Goal3(Goal3) style goal

    %% Conditions
    Entity1 --> Condition1(Cond1) style condition
    Entity2 --> Condition2(Cond2) style condition
    Entity3 --> Condition3(Cond3) style condition

    %% Decision Variables
    Entity1 --> DecisionVar1(DecVar1) style decision
    Entity2 --> DecisionVar2(DecVar2) style decision
    Entity3 --> DecisionVar3(DecVar3) style decision