
---

### ✅ **5. Mermaid.js Graph (mmd)**

```mmd
graph TD
    %% === Entities (Blue) ===
    Project[Project]:::entity
    Team[Team]:::entity
    Worker[Worker]:::entity
    Feature[Feature]:::entity
    Skill[Skill]:::entity
    Role[Role]:::entity
    ProductOwner[ProductOwner]:::entity
    ScrumMaster[ScrumMaster]:::entity
    ProductBacklog[ProductBacklog]:::entity
    Sprint[Sprint]:::entity
    SprintPlanning[SprintPlanning]:::entity
    DailyScrum[DailyScrum]:::entity
    SprintReview[SprintReview]:::entity
    SprintRetrospective[SprintRetrospective]:::entity
    SprintBacklog[SprintBacklog]:::entity
    SprintGoal[SprintGoal]:::entity
    Epic[Epic]:::entity
    UserStory[UserStory]:::entity
    Task[Task]:::entity
    DevelopmentSnapshot[DevelopmentSnapshot]:::entity
    Blocker[Blocker]:::entity
    Stakeholder[Stakeholder]:::entity
    Velocity[Velocity]:::entity
    ReleasePlan[ReleasePlan]:::entity
    Roadmap[Roadmap]:::entity
    ScrumBoard[ScrumBoard]:::entity
    FeatureDocumentation[FeatureDocumentation]:::entity

    %% === Attributes (White) ===
    id1[(id)]:::attribute
    name1[(name)]:::attribute
    project_start[(project_start)]:::attribute
    project_end[(project_end)]:::attribute
    description1[(description)]:::attribute
    budget[(budget)]:::attribute
    status1[(status)]:::attribute
    target_audience[(target_audience)]:::attribute
    priority1[(priority)]:::attribute

    team_size[(team_size)]:::attribute
    team_start[(team_start)]:::attribute
    team_status[(team_status)]:::attribute
    location[(location)]:::attribute
    team_type[(team_type)]:::attribute

    first_name[(first_name)]:::attribute
    email1[(email)]:::attribute
    start_date[(start_date)]:::attribute
    availability[(availability)]:::attribute

    title1[(title)]:::attribute
    estimated_effort[(estimated_effort)]:::attribute

    label[(label)]:::attribute
    level[(level)]:::attribute
    certified[(certified)]:::attribute
    category[(category)]:::attribute

    role_name[(role_name)]:::attribute
    area_of_responsibility[(area_of_responsibility)]:::attribute

    created_on[(created_on)]:::attribute
    last_updated[(last_updated)]:::attribute
    number_of_entries[(number_of_entries)]:::attribute

    sprint_number[(sprint_number)]:::attribute
    achievement_of_goal[(achievement_of_goal)]:::attribute

    date1[(date)]:::attribute
    duration_min[(duration_(min))]:::attribute
    moderation[(moderation)]:::attribute
    outcome_documentation[(outcome_documentation)]:::attribute

    feedback_documentation[(feedback_documentation)]:::attribute
    attendees_count[(attendees_count)]:::attribute

    improvement_actions[(improvement_actions)]:::attribute
    team_satisfaction[(team_satisfaction)]:::attribute

    number_of_tasks[(number_of_tasks)]:::attribute
    total_effort[(total_effort)]:::attribute

    objective_description[(objective_description)]:::attribute
    benefit[(benefit)]:::attribute

    change_log[(change_log)]:::attribute
    linked_requirements[(linked_requirements)]:::attribute
    author[(author)]:::attribute

    version_number[(version_number)]:::attribute
    test_status[(test_status)]:::attribute
    deployment_target[(deployment_target)]:::attribute
    documentation[(documentation)]:::attribute

    severity[(severity)]:::attribute
    detected_on[(detected_on)]:::attribute
    resolved_on[(resolved_on)]:::attribute

    organization[(organization)]:::attribute
    area_of_interest[(area_of_interest)]:::attribute
    influence_level[(influence_level)]:::attribute
    relevance_to_feature[(relevance_to_feature)]:::attribute

    number_of_sprints_used[(number_of_sprints_used)]:::attribute
    avg_story_points[(avg._story_points)]:::attribute
    max_velocity[(max_velocity)]:::attribute
    min_velocity[(min_velocity)]:::attribute
    trend[(trend)]:::attribute

    version[(version)]:::attribute
    planned_date[(planned_date)]:::attribute
    included_features[(included_features)]:::attribute

    start_date_rm[(start_date)]:::attribute
    end_date_rm[(end_date)]:::attribute
    milestones[(milestones)]:::attribute
    objectives[(objectives)]:::attribute
    versions[(versions)]:::attribute

    board_type[(board_type)]:::attribute
    columns_todo_done[(columns_(todo/done...))]:::attribute
    number_of_cards[(number_of_cards)]:::attribute

    creation_date[(creation_date)]:::attribute

    %% === Relations (Orange) ===
    R1[is_assigned_to_project]:::relation
    R2[belongs_to_team]:::relation
    R3[has_skill]:::relation
    R4[takes_on_role]:::relation
    R5[manages_backlog]:::relation
    R6[is_supported_by]:::relation
    R7[contains_feature]:::relation
    R8[contains_epic]:::relation
    R9[contains_user_story]:::relation
    R10[consists_of_tasks]:::relation
    R11[is_in_sprint_backlog]:::relation
    R12[belongs_to_sprint]:::relation
    R13[pursues_goal]:::relation
    R14[contains_tasks]:::relation
    R15[documents_feature]:::relation
    R16[is_blocked_by]:::relation
    R17[participates_in]:::relation
    R18[moderates_retrospective]:::relation
    R19[refers_to_team]:::relation
    R20[plans_release]:::relation
    R21[is_part_of_roadmap]:::relation
    R22[generates_snapshot]:::relation

    %% === Goals (Green) ===
    G0[maximize_project_priority]:::goal
    G1[minimize_project_duration]:::goal
    G2[maximize_team_size]:::goal
    G3[minimize_worker_unavailability]:::goal
    G4[maximize_skill_certification]:::goal
    G5[maximize_feature_priority]:::goal
    G6[minimize_sprint_duration]:::goal
    G7[maximize_sprint_achievement]:::goal
    G8[maximize_story_points_completed]:::goal
    G9[minimize_blocker_severity]:::goal
    G10[maximize_stakeholder_influence]:::goal
    G11[maximize_velocity_trend]:::goal
    G12[minimize_release_delay]:::goal
    G13[maximize_documentation_coverage]:::goal
    G14[maximize_daily_scrum_attendance]:::goal

    %% === Conditions (Red) ===
    C0[require_project_status_active]:::condition
    C1[require_team_status_active]:::condition
    C2[require_worker_status_active]:::condition
    C3[require_feature_status_not_done]:::condition
    C4[require_sprint_status_active]:::condition
    C5[require_task_status_not_done]:::condition
    C6[require_user_story_priority_above_threshold]:::condition
    C7[require_skill_level_above_intermediate]:::condition
    C8[require_blocker_status_open]:::condition
    C9[require_stakeholder_relevance_high]:::condition
    C10[require_velocity_min_value]:::condition
    C11[require_sprint_goal_defined]:::condition
    C12[require_release_status_planned]:::condition
    C13[require_board_updated_recently]:::condition
    C14[require_documentation_author_assigned]:::condition

    %% === Decision Variables (Purple) ===
    DV0[assign_worker_to_task]:::decisionvar
    DV1[select_feature_for_sprint]:::decisionvar
    DV2[plan_sprint_duration]:::decisionvar
    DV3[allocate_budget_to_project]:::decisionvar
    DV4[schedule_daily_scrum]:::decisionvar
    DV5[activate_team]:::decisionvar
    DV6[start_project]:::decisionvar
    DV7[resolve_blocker]:::decisionvar
    DV8[approve_release]:::decisionvar
    DV9[update_documentation]:::decisionvar
    DV10[moderate_retrospective]:::decisionvar
    DV11[estimate_story_points]:::decisionvar
    DV12[define_sprint_goal]:::decisionvar
    DV13[track_velocity]:::decisionvar
    DV14[invite_stakeholder]:::decisionvar

    %% === Entity-Attribute Links ===
    Project --> id1
    Project --> name1
    Project --> project_start
    Project --> project_end
    Project --> description1
    Project --> budget
    Project --> status1
    Project --> target_audience
    Project --> priority1

    Team --> id1
    Team --> name1
    Team --> team_size
    Team --> team_start
    Team --> team_status
    Team --> location
    Team --> team_type

    Worker --> id1
    Worker --> name1
    Worker --> first_name
    Worker --> email1
    Worker --> start_date
    Worker --> status1
    Worker --> availability

    Feature --> id1
    Feature --> title1
    Feature --> description1
    Feature --> status1
    Feature --> priority1
    Feature --> estimated_effort

    Skill --> id1
    Skill --> label
    Skill --> description1
    Skill --> level
    Skill --> certified
    Skill --> category

    Role --> id1
    Role --> role_name
    Role --> description1
    Role --> area_of_responsibility

    ProductOwner --> id1
    ProductOwner --> name1
    ProductOwner --> email1
    ProductOwner --> availability

    ScrumMaster --> id1
    ScrumMaster --> name1
    ScrumMaster --> email1
    ScrumMaster --> experience

    ProductBacklog --> id1
    ProductBacklog --> created_on
    ProductBacklog --> last_updated
    ProductBacklog --> number_of_entries
    ProductBacklog --> status1

    Sprint --> id1
    Sprint --> sprint_number
    Sprint --> start_date
    Sprint --> end_date
    Sprint --> status1
    Sprint --> achievement_of_goal

    SprintPlanning --> id1
    SprintPlanning --> date1
    SprintPlanning --> duration_min
    SprintPlanning --> moderation
    SprintPlanning --> outcome_documentation

    DailyScrum --> id1
    DailyScrum --> date1
    DailyScrum --> time
    DailyScrum --> duration_min
    DailyScrum --> moderation

    SprintReview --> id1
    SprintReview --> date1
    SprintReview --> duration_min
    SprintReview --> feedback_documentation
    SprintReview --> attendees_count

    SprintRetrospective --> id1
    SprintRetrospective --> date1
    SprintRetrospective --> duration_min
    SprintRetrospective --> improvement_actions
    SprintRetrospective --> team_satisfaction
    SprintRetrospective --> moderation

    SprintBacklog --> id1
    SprintBacklog --> number_of_tasks
    SprintBacklog --> last_updated
    SprintBacklog --> status1
    SprintBacklog --> total_effort

    SprintGoal --> id1
    SprintGoal --> objective_description
    SprintGoal --> achievement_status
    SprintGoal --> benefit

    Epic --> id1
    Epic --> title1
    Epic --> description1
    Epic --> priority1
    Epic --> status1
    Epic --> estimated_effort

    UserStory --> id1
    UserStory --> title1
    UserStory --> description1
    UserStory --> acceptance_criteria
    UserStory --> priority1
    UserStory --> story_points
    UserStory --> status1

    Task --> id1
    Task --> title1
    Task --> description1
    Task --> status1
    Task --> effort
    Task --> type

    DevelopmentSnapshot --> id1
    DevelopmentSnapshot --> version_number
    DevelopmentSnapshot --> creation_date
    DevelopmentSnapshot --> test_status
    DevelopmentSnapshot --> deployment_target
    DevelopmentSnapshot --> documentation

    Blocker --> id1
    Blocker --> title1
    Blocker --> description1
    Blocker --> severity
    Blocker --> status1
    Blocker --> detected_on
    Blocker --> resolved_on

    Stakeholder --> id1
    Stakeholder --> name1
    Stakeholder --> organization
    Stakeholder --> role
    Stakeholder --> email1
    Stakeholder --> area_of_interest
    Stakeholder --> influence_level
    Stakeholder --> relevance_to_feature

    Velocity --> id1
    Velocity --> number_of_sprints_used
    Velocity --> avg_story_points
    Velocity --> max_velocity
    Velocity --> min_velocity
    Velocity --> trend

    ReleasePlan --> id1
    ReleasePlan --> version
    ReleasePlan --> planned_date
    ReleasePlan --> included_features
    ReleasePlan --> status1

    Roadmap --> id1
    Roadmap --> start_date_rm
    Roadmap --> end_date_rm
    Roadmap --> milestones
    Roadmap --> objectives
    Roadmap --> versions

    ScrumBoard --> id1
    ScrumBoard --> board_type
    ScrumBoard --> columns_todo_done
    ScrumBoard --> number_of_cards
    ScrumBoard --> last_updated

    FeatureDocumentation --> id1
    FeatureDocumentation --> title1
    FeatureDocumentation --> description1
    FeatureDocumentation --> creation_date
    FeatureDocumentation --> change_log
    FeatureDocumentation --> linked_requirements
    FeatureDocumentation --> author

    %% === Entity-Relation Links ===
    Team --> R1 --> Project
    Worker --> R2 --> Team
    Worker --> R3 --> Skill
    Worker --> R4 --> Role
    ProductOwner --> R5 --> ProductBacklog
    Team --> R6 --> ScrumMaster
    ProductBacklog --> R7 --> Feature
    ProductBacklog --> R8 --> Epic
    Epic --> R9 --> UserStory
    UserStory --> R10 --> Task
    UserStory --> R11 --> SprintBacklog
    SprintBacklog --> R12 --> Sprint
    Sprint --> R13 --> SprintGoal
    ScrumBoard --> R14 --> Task
    FeatureDocumentation --> R15 --> Feature
    Task --> R16 --> Blocker
    Stakeholder --> R17 --> SprintReview
    ScrumMaster --> R18 --> SprintRetrospective
    Velocity --> R19 --> Team
    ReleasePlan --> R20 --> Feature
    ReleasePlan --> R21 --> Roadmap
    Sprint --> R22 --> DevelopmentSnapshot

    %% === Goal-Entity/Attribute Links ===
    G0 --> priority1
    G1 --> project_end
    G2 --> team_size
    G3 --> status1
    G4 --> certified
    G5 --> priority1
    G6 --> duration_min
    G7 --> achievement_of_goal
    G8 --> story_points
    G9 --> severity
    G10 --> influence_level
    G11 --> trend
    G12 --> planned_date
    G13 --> linked_requirements
    G14 --> date1

    %% === Condition-Entity/Attribute Links ===
    C0 --> status1
    C1 --> team_status
    C2 --> status1
    C3 --> status1
    C4 --> status1
    C5 --> status1
    C6 --> priority1
    C7 --> level
    C8 --> status1
    C9 --> relevance_to_feature
    C10 --> avg_story_points
    C11 --> objective_description
    C12 --> status1
    C13 --> last_updated
    C14 --> author

    %% === DecisionVariable-Entity Links ===
    DV0 --> Worker
    DV0 --> Task
    DV1 --> Feature
    DV1 --> Sprint
    DV2 --> Sprint
    DV3 --> Project
    DV4 --> DailyScrum
    DV5 --> Team
    DV6 --> Project
    DV7 --> Blocker
    DV8 --> ReleasePlan
    DV9 --> FeatureDocumentation
    DV10 --> SprintRetrospective
    DV11 --> UserStory
    DV12 --> SprintGoal
    DV13 --> Velocity
    DV14 --> Stakeholder

    %% === Styling ===
    classDef entity fill:#1f77b4,stroke:#000,color:white,font-weight:bold;
    classDef attribute fill:#ffffff,stroke:#333,stroke-width:1px,color:black;
    classDef relation fill:#ff8c00,stroke:#000,color:white,font-weight:bold;
    classDef goal fill:#2ca02c,stroke:#000,color:white,font-weight:bold;
    classDef condition fill:#d62728,stroke:#000,color:white,font-weight:bold;
    classDef decisionvar fill:#9467bd,stroke:#000,color:white,font-weight:bold;