graph LR
classDef entity fill:#d1b3ff,stroke:#333;
classDef variable fill:#99e699,stroke:#333;
classDef goal fill:#99ccff,stroke:#333;
classDef constraint fill:#ff9999,stroke:#333;
classDef relationship fill:#ffe066,stroke:#333;

entity1 --> variable1
entity2 --> variable2

variable1 --[constraint: constraint1]--> entity1
variable2 --[constraint: constraint2]--> entity2

entity1 --[relationship: relationship1]--> entity2
entity1 --[goal: goal1]--> goal1
entity2 --[goal: goal2]--> goal2

classDef(entity, variable, goal, constraint, relationship)