graph TD
  subgraph entities_attributes_relations
    classStyle blue
    A[Entity1] --> B[Attribute1]
    C[Entity2] --> D[Attribute2]
    E[Entity3] --> F[Attribute3]
  
    classStyle orange
    G[Relation1] --> A
    H[Relation2] --> C
  
  subgraph goals_conditions_decision_variables
    classStyle green
    I[Goal1] --> J[Entity/Attributes]
    
    classStyle red
    K[Condition1] --> L[Entity/Attributes]
  
    classStyle purple
    M[DecisionVariable1] --> N[RelevantEntity/Attribute]
  end