graph TD
subgraph Entities
  A[Entity1] --> B[Attribute1]
  C[Entity2] --> D[Attribute2]
  E[Entity3] --> F[Attribute3]

  A - rightof - B
  C - rightof - D
  E - rightof - F
end

subgraph Relations
  G(Entities) --> H(Relation1)
  I(Entities) --> J(Relation2)
  
  G --> K[Entity4]
  I --> L[Entity5]

  H - rightof - G
  J - rightof - I
  K -- Relation3 --> L
end

subgraph Goals
  M[Goal1] --> N[Entity/Attribute]
end

subgraph Conditions
  O[Condition1] --> P[Entity/Attribute]
end

subgraph DecisionVariables
  Q[DecisionVariable1] --> R[Entity/Attribute]
end

style A fill:#FF00FF,stroke:none; 
style B fill:#FFFFFF,stroke:#000000,stroke-width:4px;
style C fill:#FF00FF,stroke:none; 
style D fill:#FFFFFF,stroke:#000000,stroke-width:4px;
style E fill:#FF00FF,stroke:none; 
style F fill:#FFFFFF,stroke:#000000,stroke-width:4px;

style G fill:#FF00FF,stroke:none; 
style H fill:#FFFF00,stroke:#000000,stroke-width:4px;
style I fill:#FF00FF,stroke:none; 
style J fill:#FFFF00,stroke:#000000,stroke-width:4px;
style K fill:#FFFFFF,stroke:#000000,stroke-width:4px;
style L fill:#FFFF00,stroke:#000000,stroke-width:4px;

style M fill:#008000,stroke:none; 
style N fill:#FFFFFF,stroke:#000000,stroke-width:4px;

style O fill:#FF0000,stroke:none; 
style P fill:#FFFFFF,stroke:#000000,stroke-width:4px;

style Q fill:#800080,stroke:none;
style R fill:#FFFFFF,stroke:#000000,stroke-width:4px;