graph TD
    %% ============ ENTITY NODES (Blue) ============
    E0[Project]:::entity
    E1[Team]:::entity
    E2[Worker]:::entity
    E3[Feature]:::entity
    E4[Skill]:::entity
    E5[Role]:::entity
    E6[ProductOwner]:::entity
    E7[ScrumMaster]:::entity
    E8[ProductBacklog]:::entity
    E9[Sprint]:::entity
    E10[SprintPlanning]:::entity
    E11[DailyScrum]:::entity
    E12[SprintReview]:::entity
    E13[SprintRetrospective]:::entity
    E14[SprintBacklog]:::entity
    E15[SprintGoal]:::entity
    E16[Epic]:::entity
    E17[UserStory]:::entity
    E18[Task]:::entity
    E19[DevelopmentSnapshot]:::entity
    E20[Blocker]:::entity
    E21[Stakeholder]:::entity
    E22[Velocity]:::entity
    E23[ReleasePlan]:::entity
    E24[Roadmap]:::entity
    E25[ScrumBoard]:::entity
    E26[FeatureDocumentation]:::entity

    %% ============ ATTRIBUTE NODES (White) ============
    A0_0[id]:::attribute
    A0_1[name]:::attribute
    A0_2[project_start]:::attribute
    A0_3[project_end]:::attribute
    A0_4[description]:::attribute
    A0_5[budget]:::attribute
    A0_6[status]:::attribute
    A0_7[target_audience]:::attribute
    A0_8[priority]:::attribute

    A1_0[id]:::attribute
    A1_1[name]:::attribute
    A1_2[team_size]:::attribute
    A1_3[team_start]:::attribute
    A1_4[team_status]:::attribute
    A1_5[location]:::attribute
    A1_6[team_type]:::attribute

    A2_0[id]:::attribute
    A2_1[name]:::attribute
    A2_2[first_name]:::attribute
    A2_3[email]:::attribute
    A2_4[start_date]:::attribute
    A2_5[status]:::attribute
    A2_6[availability]:::attribute

    A3_0[id]:::attribute
    A3_1[title]:::attribute
    A3_2[description]:::attribute
    A3_3[status]:::attribute
    A3_4[priority]:::attribute
    A3_5[estimated_effort]:::attribute

    A4_0[id]:::attribute
    A4_1[label]:::attribute
    A4_2[description]:::attribute
    A4_3[level]:::attribute
    A4_4[certified]:::attribute
    A4_5[category]:::attribute

    A5_0[id]:::attribute
    A5_1[role_name]:::attribute
    A5_2[description]:::attribute
    A5_3[area_of_responsibility]:::attribute

    A6_0[id]:::attribute
    A6_1[name]:::attribute
    A6_2[email]:::attribute
    A6_3[availability]:::attribute

    A7_0[id]:::attribute
    A7_1[name]:::attribute
    A7_2[email]:::attribute
    A7_3[experience]:::attribute

    A8_0[id]:::attribute
    A8_1[created_on]:::attribute
    A8_2[last_updated]:::attribute
    A8_3[number_of_entries]:::attribute
    A8_4[status]:::attribute

    A9_0[id]:::attribute
    A9_1[sprint_number]:::attribute
    A9_2[start_date]:::attribute
    A9_3[end_date]:::attribute
    A9_4[status]:::attribute
    A9_5[achievement_of_goal]:::attribute

    A10_0[id]:::attribute
    A10_1[date]:::attribute
    A10_2[duration_(min)]:::attribute
    A10_3[moderation]:::attribute
    A10_4[outcome_documentation]:::attribute

    A11_0[id]:::attribute
    A11_1[date]:::attribute
    A11_2[time]:::attribute
    A11_3[duration]:::attribute
    A11_4[moderation]:::attribute

    A12_0[id]:::attribute
    A12_1[date]:::attribute
    A12_2[duration]:::attribute
    A12_3[feedback_documentation]:::attribute
    A12_4[attendees_count]:::attribute

    A13_0[id]:::attribute
    A13_1[date]:::attribute
    A13_2[duration]:::attribute
    A13_3[improvement_actions]:::attribute
    A13_4[team_satisfaction]:::attribute
    A13_5[moderation]:::attribute

    A14_0[id]:::attribute
    A14_1[number_of_tasks]:::attribute
    A14_2[last_updated]:::attribute
    A14_3[status]:::attribute
    A14_4[total_effort]:::attribute

    A15_0[id]:::attribute
    A15_1[objective_description]:::attribute
    A15_2[achievement_status]:::attribute
    A15_3[benefit]:::attribute

    A16_0[id]:::attribute
    A16_1[title]:::attribute
    A16_2[description]:::attribute
    A16_3[priority]:::attribute
    A16_4[status]:::attribute
    A16_5[estimated_effort]:::attribute

    A17_0[id]:::attribute
    A17_1[title]:::attribute
    A17_2[description]:::attribute
    A17_3[acceptance_criteria]:::attribute
    A17_4[priority]:::attribute
    A17_5[story_points]:::attribute
    A17_6[status]:::attribute

    A18_0[id]:::attribute
    A18_1[title]:::attribute
    A18_2[description]:::attribute
    A18_3[status]:::attribute
    A18_4[effort]:::attribute
    A18_5[type]:::attribute

    A19_0[id]:::attribute
    A19_1[version_number]:::attribute
    A19_2[creation_date]:::attribute
    A19_3[test_status]:::attribute
    A19_4[deployment_target]:::attribute
    A19_5[documentation]:::attribute

    A20_0[id]:::attribute
    A20_1[title]:::attribute
    A20_2[description]:::attribute
    A20_3[severity]:::attribute
    A20_4[status]:::attribute
    A20_5[detected_on]:::attribute
    A20_6[resolved_on]:::attribute

    A21_0[id]:::attribute
    A21_1[name]:::attribute
    A21_2[organization]:::attribute
    A21_3[role]:::attribute
    A21_4[email]:::attribute
    A21_5[area_of_interest]:::attribute
    A21_6[influence_level]:::attribute
    A21_7[relevance_to_feature]:::attribute

    A22_0[id]:::attribute
    A22_1[number_of_sprints_used]:::attribute
    A22_2[avg._story_points]:::attribute
    A22_3[max_velocity]:::attribute
    A22_4[min_velocity]:::attribute
    A22_5[trend]:::attribute

    A23_0[id]:::attribute
    A23_1[version]:::attribute
    A23_2[planned_date]:::attribute
    A23_3[included_features]:::attribute
    A23_4[status]:::attribute

    A24_0[id]:::attribute
    A24_1[start_date]:::attribute
    A24_2[end_date]:::attribute
    A24_3[milestones]:::attribute
    A24_4[objectives]:::attribute
    A24_5[versions]:::attribute

    A25_0[id]:::attribute
    A25_1[board_type]:::attribute
    A25_2[columns_(todo/done...)]:::attribute
    A25_3[number_of_cards]:::attribute
    A25_4[last_updated]:::attribute

    A26_0[id]:::attribute
    A26_1[title]:::attribute
    A26_2[description]:::attribute
    A26_3[creation_date]:::attribute
    A26_4[change_log]:::attribute
    A26_5[linked_requirements]:::attribute
    A26_6[author]:::attribute

    %% ============ RELATION NODES (Orange) ============
    R1[is_assigned_to_project]:::relation
    R2[belongs_to_team]:::relation
    R3[has_skill]:::relation
    R4[takes_on_role]:::relation
    R5[manages_backlog]:::relation
    R6[is_supported_by]:::relation
    R7[contains_feature]:::relation
    R8[contains_epic]:::relation
    R9[contains_user_story]:::relation
    R10[consists_of_tasks]:::relation
    R11[is_in_sprint_backlog]:::relation
    R12[belongs_to_sprint]:::relation
    R13[pursues_goal]:::relation
    R14[contains_tasks]:::relation
    R15[documents_feature]:::relation
    R16[is_blocked_by]:::relation
    R17[participates_in]:::relation
    R18[moderates_retrospective]:::relation
    R19[refers_to_team]:::relation
    R20[plans_release]:::relation
    R21[is_part_of_roadmap]:::relation
    R22[generates_snapshot]:::relation

    %% ============ GOAL NODES (Green) ============
    G0[maximize_project_budget]:::goal
    G1[maximize_team_size]:::goal
    G2[maximize_story_points]:::goal
    G3[minimize_sprint_duration]:::goal
    G4[maximize_velocity_trend]:::goal
    G5[maximize_worker_availability]:::goal
    G6[minimize_task_effort]:::goal
    G7[maximize_feature_priority]:::goal
    G8[minimize_epic_estimated_effort]:::goal
    G9[maximize_stakeholder_influence]:::goal
    G10[minimize_blocker_severity]:::goal
    G11[maximize_sprint_goal_achievement]:::goal
    G12[minimize_daily_scrum_duration]:::goal
    G13[maximize_release_plan_included_features]:::goal
    G14[maximize_documentation_linking]:::goal

    %% ============ CONDITION NODES (Red) ============
    C0[ensure_product_owner_assigned]:::condition
    C1[require_scrum_master_per_team]:::condition
    C2[task_must_have_status]:::condition
    C3[user_story_must_have_priority]:::condition
    C4[project_must_be_active]:::condition
    C5[worker_must_be_active]:::condition
    C6[sprint_must_be_current]:::condition
    C7[blocker_must_be_tracked]:::condition
    C8[velocity_based_on_recent_sprints]:::condition
    C9[feature_must_have_title]:::condition
    C10[documentation_must_have_author]:::condition
    C11[release_plan_must_have_date]:::condition
    C12[scrum_board_must_be_updated]:::condition
    C13[worker_email_required]:::condition
    C14[epic_must_have_estimated_effort]:::condition

    %% ============ DECISION VARIABLE NODES (Purple) ============
    DV0[assign_worker_to_task]:::decisionvar
    DV1[task_effort_allocation]:::decisionvar
    DV2[sprint_duration]:::decisionvar
    DV3[team_size]:::decisionvar
    DV4[story_points_estimate]:::decisionvar
    DV5[worker_availability_percentage]:::decisionvar
    DV6[feature_priority_level]:::decisionvar
    DV7[blocker_severity_level]:::decisionvar
    DV8[velocity_avg_story_points]:::decisionvar
    DV9[planned_release_version]:::decisionvar
    DV10[number_of_sprints_in_velocity]:::decisionvar
    DV11[scrum_board_column_count]:::decisionvar
    DV12[documentation_change_count]:::decisionvar
    DV13[daily_scrum_duration_minutes]:::decisionvar
    DV14[team_satisfaction_score]:::decisionvar

    %% ============ ENTITY TO ATTRIBUTE CONNECTIONS ============
    E0 --> A0_0; E0 --> A0_1; E0 --> A0_2; E0 --> A0_3; E0 --> A0_4; E0 --> A0_5; E0 --> A0_6; E0 --> A0_7; E0 --> A0_8
    E1 --> A1_0; E1 --> A1_1; E1 --> A1_2; E1 --> A1_3; E1 --> A1_4; E1 --> A1_5; E1 --> A1_6
    E2 --> A2_0; E2 --> A2_1; E2 --> A2_2; E2 --> A2_3; E2 --> A2_4; E2 --> A2_5; E2 --> A2_6
    E3 --> A3_0; E3 --> A3_1; E3 --> A3_2; E3 --> A3_3; E3 --> A3_4; E3 --> A3_5
    E4 --> A4_0; E4 --> A4_1; E4 --> A4_2; E4 --> A4_3; E4 --> A4_4; E4 --> A4_5
    E5 --> A5_0; E5 --> A5_1; E5 --> A5_2; E5 --> A5_3
    E6 --> A6_0; E6 --> A6_1; E6 --> A6_2; E6 --> A6_3
    E7 --> A7_0; E7 --> A7_1; E7 --> A7_2; E7 --> A7_3
    E8 --> A8_0; E8 --> A8_1; E8 --> A8_2; E8 --> A8_3; E8 --> A8_4
    E9 --> A9_0; E9 --> A9_1; E9 --> A9_2; E9 --> A9_3; E9 --> A9_4; E9 --> A9_5
    E10 --> A10_0; E10 --> A10_1; E10 --> A10_2; E10 --> A10_3; E10 --> A10_4
    E11 --> A11_0; E11 --> A11_1; E11 --> A11_2; E11 --> A11_3; E11 --> A11_4
    E12 --> A12_0; E12 --> A12_1; E12 --> A12_2; E12 --> A12_3; E12 --> A12_4
    E13 --> A13_0; E13 --> A13_1; E13 --> A13_2; E13 --> A13_3; E13 --> A13_4; E13 --> A13_5
    E14 --> A14_0; E14 --> A14_1; E14 --> A14_2; E14 --> A14_3; E14 --> A14_4
    E15 --> A15_0; E15 --> A15_1; E15 --> A15_2; E15 --> A15_3
    E16 --> A16_0; E16 --> A16_1; E16 --> A16_2; E16 --> A16_3; E16 --> A16_4; E16 --> A16_5
    E17 --> A17_0; E17 --> A17_1; E17 --> A17_2; E17 --> A17_3; E17 --> A17_4; E17 --> A17_5; E17 --> A17_6
    E18 --> A18_0; E18 --> A18_1; E18 --> A18_2; E18 --> A18_3; E18 --> A18_4; E18 --> A18_5
    E19 --> A19_0; E19 --> A19_1; E19 --> A19_2; E19 --> A19_3; E19 --> A19_4; E19 --> A19_5
    E20 --> A20_0; E20 --> A20_1; E20 --> A20_2; E20 --> A20_3; E20 --> A20_4; E20 --> A20_5; E20 --> A20_6
    E21 --> A21_0; E21 --> A21_1; E21 --> A21_2; E21 --> A21_3; E21 --> A21_4; E21 --> A21_5; E21 --> A21_6; E21 --> A21_7
    E22 --> A22_0; E22 --> A22_1; E22 --> A22_2; E22 --> A22_3; E22 --> A22_4; E22 --> A22_5
    E23 --> A23_0; E23 --> A23_1; E23 --> A23_2; E23 --> A23_3; E23 --> A23_4
    E24 --> A24_0; E24 --> A24_1; E24 --> A24_2; E24 --> A24_3; E24 --> A24_4; E24 --> A24_5
    E25 --> A25_0; E25 --> A25_1; E25 --> A25_2; E25 --> A25_3; E25 --> A25_4
    E26 --> A26_0; E26 --> A26_1; E26 --> A26_2; E26 --> A26_3; E26 --> A26_4; E26 --> A26_5; E26 --> A26_6

    %% ============ RELATION CONNECTIONS (Entity to Entity via Relation Node) ============
    R1 --> E0 & E1
    R2 --> E2 & E1
    R3 --> E2 & E4
    R4 --> E2 & E5
    R5 --> E6 & E8
    R6 --> E1 & E7
    R7 --> E8 & E3
    R8 --> E8 & E16
    R9 --> E16 & E17
    R10 --> E17 & E18
    R11 --> E17 & E14
    R12 --> E14 & E9
    R13 --> E9 & E15
    R14 --> E25 & E18
    R15 --> E26 & E3
    R16 --> E18 & E20
    R17 --> E21 & E12
    R18 --> E7 & E13
    R19 --> E22 & E1
    R20 --> E23 & E3
    R21 --> E23 & E24
    R22 --> E9 & E19

    %% ============ GOAL TO ENTITY + ATTRIBUTE CONNECTIONS ============
    G0 --> A0_5 & E0
    G1 --> A1_2 & E1
    G2 --> A17_5 & E17
    G3 --> A9_3 & A9_2 & E9
    G4 --> A22_5 & E22
    G5 --> A2_6 & E2
    G6 --> A18_4 & E18
    G7 --> A3_4 & E3
    G8 --> A16_5 & E16
    G9 --> A21_6 & E21
    G10 --> A20_3 & E20
    G11 --> A15_2 & E15
    G12 --> A11_3 & E11
    G13 --> A23_3 & E23
    G14 --> A26_5 & E26

    %% ============ CONDITION TO ENTITY + ATTRIBUTE CONNECTIONS ============
    C0 --> A6_0 & E6 & E8 & E0
    C1 --> A7_0 & E7 & E1
    C2 --> A18_3 & E18
    C3 --> A17_4 & E17
    C4 --> A0_6 & E0
    C5 --> A2_5 & E2
    C6 --> A9_4 & E9
    C7 --> A20_5 & E20
    C8 --> A22_1 & E22
    C9 --> A3_1 & E3
    C10 --> A26_6 & E26
    C11 --> A23_2 & E23
    C12 --> A25_4 & E25
    C13 --> A2_3 & E2
    C14 --> A16_5 & E16

    %% ============ DECISION VARIABLE TO ENTITY CONNECTIONS ============
    DV0 --> E2 & E18
    DV1 --> E18
    DV2 --> E9
    DV3 --> E1
    DV4 --> E17
    DV5 --> E2
    DV6 --> E3
    DV7 --> E20
    DV8 --> E22
    DV9 --> E23
    DV10 --> E22
    DV11 --> E25
    DV12 --> E26
    DV13 --> E11
    DV14 --> E13

    %% ============ STYLING ============
    classDef entity fill:#1f77b4,stroke:#005580,stroke-width:2px,color:white,font-weight:bold;
    classDef attribute fill:#ffffff,stroke:#333,stroke-width:1px,color:#333;
    classDef relation fill:#ff8c00,stroke:#cc6600,stroke-width:2px,color:white,font-weight:bold;
    classDef goal fill:#2ca02c,stroke:#006400,stroke-width:2px,color:white,font-weight:bold;
    classDef condition fill:#d62728,stroke:#990000,stroke-width:2px,color:white,font-weight:bold;
    classDef decisionvar fill:#9467bd,stroke:#6a1b9a,stroke-width:2px,color:white,font-weight:bold;