ID,Name,Description,IsSum,GoalType,EntityName,EntityAttribute,CriteriaType,Weight
G0,maximize_project_completion,Maximize the number of completed projects,False,max,Project,status,2,1.0
G1,maximize_team_efficiency,Maximize team efficiency by minimizing blockers,False,max,Task,status,2,1.0
G2,maximize_stakeholder_satisfaction,Maximize stakeholder satisfaction through feature documentation,False,max,FeatureDocumentation,change_log,2,1.0
G3,minimize_blockers,Minimize the number of blockers in tasks,False,min,Blocker,status,2,1.0
G4,maximize_feature_completion,Maximize the number of completed features,False,max,Feature,status,2,1.0
G5,maximize_sprint_velocity,Maximize the average velocity of the team,False,max,Velocity,avg._story_points,2,1.0
G6,minimize_budget_exceedance,Minimize the budget exceedance of projects,False,min,Project,budget,2,1.0
G7,maximize_story_points_completed,Maximize the number of story points completed in sprints,False,max,Sprint,achievement_of_goal,2,1.0
G8,maximize_task_completion,Maximize the number of completed tasks,False,max,Task,status,2,1.0
G9,maximize_user_story_completion,Maximize the number of completed user stories,False,max,UserStory,status,2,1.0
G10,maximize_sprint_goal_achievement,Maximize the achievement of sprint goals,False,max,SprintGoal,achievement_status,2,1.0
G11,maximize_feature_documentation_completeness,Maximize the completeness of feature documentation,False,max,FeatureDocumentation,change_log,2,1.0
G12,maximize_epic_completion,Maximize the number of completed epics,False,max,Epic,status,2,1.0
G13,maximize_team_satisfaction,Maximize team satisfaction through retrospectives,False,max,SprintRetrospective,team_satisfaction,2,1.0
G14,minimize_sprint_overrun,Minimize the overrun of sprints,False,min,Sprint,status,2,1.0
G15,maximize_release_plan_completion,Maximize the completion of release plans,False,max,ReleasePlan,status,2,1.0