graph TD
    A[Entities] -> B[Attributes]
        B -> C[Skeletons] || 2
    D[Entities] -> E[Relations] || 3
    F[Goals] <- G[Goals] <- H[Conditions] <- I[DecisionVariables]
    J[Tasks] <- K[ScrumBoard] <- L[F board] <- M[U story] <- N[Fibonacci] <- O[Epics] <- P[U Stories] <- Q[UserStories]
    R[ProductBacklog] -> S[Feature] -> T[UserStory] <- U[Team] <- V[Employee] <- W[Skills] <- X[Roles] <- Y[ProductOwner] <- Z[ScrumMaster]