graph TD
    %% Styling
    classDef entity fill:#87CEFA,color:#000,stroke:#000;
    classDef attribute fill:#FFF,color:#000,stroke:#333;
    classDef relation fill:#FFA500,color:#000,stroke:#000;
    classDef goal fill:#90EE90,color:#000,stroke:#000;
    classDef condition fill:#F08080,color:#000,stroke:#000;
    classDef dv fill:#DDA0DD,color:#000,stroke:#000;

    %% Entities
    E0[Project]; E1[Team]; E2[Worker]; E3[Feature]; E4[Skill]; E5[Role]; E6[ProductOwner]; E7[ScrumMaster]; E8[ProductBacklog]; E9[Sprint]; E10[SprintPlanning]; E11[DailyScrum]; E12[SprintReview]; E13[SprintRetrospective]; E14[SprintBacklog]; E15[SprintGoal]; E16[Epic]; E17[UserStory]; E18[Task]; E19[DevelopmentSnapshot]; E20[Blocker]; E21[Stakeholder]; E22[Velocity]; E23[ReleasePlan]; E24[Roadmap]; E25[ScrumBoard]; E26[FeatureDocumentation];
    class E0,E1,E2,E3,E4,E5,E6,E7,E8,E9,E10,E11,E12,E13,E14,E15,E16,E17,E18,E19,E20,E21,E22,E23,E24,E25,E26 entity;

    %% Attributes
    E0_attr0(id); E0_attr1(name); E0_attr2(project_start); E0_attr3(project_end); E0_attr4(description); E0_attr5(budget); E0_attr6(status); E0_attr7(target_audience); E0_attr8(priority);
    E1_attr0(id); E1_attr1(name); E1_attr2(team_size); E1_attr3(team_start); E1_attr4(team_status); E1_attr5(location); E1_attr6(team_type);
    E2_attr0(id); E2_attr1(name); E2_attr2(first_name); E2_attr3(email); E2_attr4(start_date); E2_attr5(status); E2_attr6(availability);
    E3_attr0(id); E3_attr1(title); E3_attr2(description); E3_attr3(status); E3_attr4(priority); E3_attr5(estimated_effort);
    E4_attr0(id); E4_attr1(label); E4_attr2(description); E4_attr3(level); E4_attr4(certified); E4_attr5(category);
    E17_attr0(id); E17_attr1(title); E17_attr2(description); E17_attr3(acceptance_criteria); E17_attr4(priority); E17_attr5(story_points); E17_attr6(status);
    E18_attr0(id); E18_attr1(title); E18_attr2(description); E18_attr3(status); E18_attr4(effort); E18_attr5(type);
    E20_attr0(id); E20_attr1(title); E20_attr2(description); E20_attr3(severity); E20_attr4(status); E20_attr5(detected_on); E20_attr6(resolved_on);
    E9_attr0(id); E9_attr1(sprint_number); E9_attr2(start_date); E9_attr3(end_date); E9_attr4(status); E9_attr5(achievement_of_goal);
    E15_attr0(id); E15_attr1(objective_description); E15_attr2(achievement_status); E15_attr3(benefit);
    E21_attr0(id); E21_attr1(name); E21_attr2(organization); E21_attr3(role); E21_attr4(email); E21_attr5(area_of_interest); E21_attr6(influence_level); E21_attr7(relevance_to_feature);
    E22_attr0(id); E22_attr1(number_of_sprints_used); E22_attr2(avg._story_points); E22_attr3(max_velocity); E22_attr4(min_velocity); E22_attr5(trend);
    E23_attr0(id); E23_attr1(version); E23_attr2(planned_date); E23_attr3(included_features); E23_attr4(status);
    E8_attr0(id); E8_attr1(created_on); E8_attr2(last_updated); E8_attr3(number_of_entries); E8_attr4(status);
    class E0_attr0,E0_attr1,E0_attr2,E0_attr3,E0_attr4,E0_attr5,E0_attr6,E0_attr7,E0_attr8,E1_attr0,E1_attr1,E1_attr2,E1_attr3,E1_attr4,E1_attr5,E1_attr6,E2_attr0,E2_attr1,E2_attr2,E2_attr3,E2_attr4,E2_attr5,E2_attr6,E3_attr0,E3_attr1,E3_attr2,E3_attr3,E3_attr4,E3_attr5,E4_attr0,E4_attr1,E4_attr2,E4_attr3,E4_attr4,E4_attr5,E17_attr0,E17_attr1,E17_attr2,E17_attr3,E17_attr4,E17_attr5,E17_attr6,E18_attr0,E18_attr1,E18_attr2,E18_attr3,E18_attr4,E18_attr5,E20_attr0,E20_attr1,E20_attr2,E20_attr3,E20_attr4,E20_attr5,E20_attr6,E9_attr0,E9_attr1,E9_attr2,E9_attr3,E9_attr4,E9_attr5,E15_attr0,E15_attr1,E15_attr2,E15_attr3,E21_attr0,E21_attr1,E21_attr2,E21_attr3,E21_attr4,E21_attr5,E21_attr6,E21_attr7,E22_attr0,E22_attr1,E22_attr2,E22_attr3,E22_attr4,E22_attr5,E23_attr0,E23_attr1,E23_attr2,E23_attr3,E23_attr4,E8_attr0,E8_attr1,E8_attr2,E8_attr3,E8_attr4 attribute;

    %% Relationships
    R1{is_assigned_to_project}; R2{belongs_to_team}; R3{has_skill}; R4{takes_on_role}; R5{manages_backlog}; R6{is_supported_by}; R7{contains_feature}; R8{contains_epic}; R9{contains_user_story}; R10{consists_of_tasks}; R11{is_in_sprint_backlog}; R12{belongs_to_sprint}; R13{pursues_goal}; R14{contains_tasks}; R15{documents_feature}; R16{is_blocked_by}; R17{participates_in}; R18{moderates_retrospective}; R19{refers_to_team}; R20{plans_release}; R21{is_part_of_roadmap}; R22{generates_snapshot};
    class R1,R2,R3,R4,R5,R6,R7,R8,R9,R10,R11,R12,R13,R14,R15,R16,R17,R18,R19,R20,R21,R22 relation;

    %% Goals
    G0((maximize_project_priority)); G1((maximize_total_story_points)); G2((minimize_project_budget_usage)); G3((minimize_task_effort)); G4((maximize_team_velocity)); G5((minimize_blocker_severity)); G6((maximize_sprint_goal_achievement)); G7((maximize_feature_priority_in_release)); G8((maximize_worker_availability)); G9((minimize_sprint_duration)); G10((maximize_stakeholder_influence)); G11((maximize_skill_level_in_team));
    class G0,G1,G2,G3,G4,G5,G6,G7,G8,G9,G10,G11 goal;

    %% Conditions
    C0((team_size_constraint)); C1((project_budget_limit)); C2((worker_assignment_limit)); C3((sprint_effort_capacity)); C4((blocker_status_for_task)); C5((feature_status_for_release)); C6((required_skill_for_task)); C7((scrum_master_per_team)); C8((unique_sprint_number)); C9((product_owner_for_backlog)); C10((task_dependency)); C11((release_plan_date)); C12((epic_story_containment));
    class C0,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12 condition;

    %% Decision Variables
    DV0>assign_worker_to_team]; DV1>assign_user_story_to_sprint]; DV2>assign_feature_to_release]; DV3>assign_task_to_worker]; DV4>select_project_for_portfolio]; DV5>sprint_start_date]; DV6>sprint_end_date]; DV7>worker_availability_percentage]; DV8>feature_priority_level]; DV9>task_effort_hours]; DV10>budget_allocation_per_project]; DV11>select_worker_for_task_with_skill];
    class DV0,DV1,DV2,DV3,DV4,DV5,DV6,DV7,DV8,DV9,DV10,DV11 dv;

    %% CONNECTIONS
    %% Entity <-> Attribute Connections
    E0 --- E0_attr0 & E0_attr1 & E0_attr2 & E0_attr3 & E0_attr4 & E0_attr5 & E0_attr6 & E0_attr7 & E0_attr8;
    E1 --- E1_attr0 & E1_attr1 & E1_attr2 & E1_attr3 & E1_attr4 & E1_attr5 & E1_attr6;
    E2 --- E2_attr0 & E2_attr1 & E2_attr2 & E2_attr3 & E2_attr4 & E2_attr5 & E2_attr6;
    E3 --- E3_attr0 & E3_attr1 & E3_attr2 & E3_attr3 & E3_attr4 & E3_attr5;
    E4 --- E4_attr0 & E4_attr1 & E4_attr2 & E4_attr3 & E4_attr4 & E4_attr5;
    E17 --- E17_attr0 & E17_attr1 & E17_attr2 & E17_attr3 & E17_attr4 & E17_attr5 & E17_attr6;
    E18 --- E18_attr0 & E18_attr1 & E18_attr2 & E18_attr3 & E18_attr4 & E18_attr5;
    E20 --- E20_attr0 & E20_attr1 & E20_attr2 & E20_attr3 & E20_attr4 & E20_attr5 & E20_attr6;
    E9 --- E9_attr0 & E9_attr1 & E9_attr2 & E9_attr3 & E9_attr4 & E9_attr5;
    E15 --- E15_attr0 & E15_attr1 & E15_attr2 & E15_attr3;
    E21 --- E21_attr0 & E21_attr1 & E21_attr2 & E21_attr3 & E21_attr4 & E21_attr5 & E21_attr6 & E21_attr7;
    E22 --- E22_attr0 & E22_attr1 & E22_attr2 & E22_attr3 & E22_attr4 & E22_attr5;
    E23 --- E23_attr0 & E23_attr1 & E23_attr2 & E23_attr3 & E23_attr4;
    E8 --- E8_attr0 & E8_attr1 & E8_attr2 & E8_attr3 & E8_attr4;

    %% Entity <-> Relation <-> Entity Connections
    E1 -- "1" --> R1 -- "N" --> E0;
    E2 -- "N" --> R2 -- "1" --> E1;
    E2 -- "N" --> R3 -- "M" --> E4;
    E2 -- "N" --> R4 -- "M" --> E5;
    E6 -- "1" --> R5 -- "1" --> E8;
    E1 -- "1" --> R6 -- "1" --> E7;
    E8 -- "1" --> R7 -- "N" --> E3;
    E8 -- "1" --> R8 -- "N" --> E16;
    E16 -- "1" --> R9 -- "N" --> E17;
    E17 -- "1" --> R10 -- "N" --> E18;
    E17 -- "N" --> R11 -- "M" --> E14;
    E14 -- "1" --> R12 -- "1" --> E9;
    E9 -- "1" --> R13 -- "1" --> E15;
    E25 -- "1" --> R14 -- "N" --> E18;
    E26 -- "1" --> R15 -- "1" --> E3;
    E18 -- "N" --> R16 -- "M" --> E20;
    E21 -- "N" --> R17 -- "M" --> E12;
    E7 -- "1" --> R18 -- "N" --> E13;
    E22 -- "1" --> R19 -- "1" --> E1;
    E23 -- "1" --> R20 -- "N" --> E3;
    E23 -- "N" --> R21 -- "1" --> E24;
    E9 -- "1" --> R22 -- "1" --> E19;

    %% Goal -> Attribute Connections
    G0 --> E0_attr8;
    G1 --> E17_attr5;
    G2 --> E0_attr5;
    G3 --> E18_attr4;
    G4 --> E22_attr2;
    G5 --> E20_attr3;
    G6 --> E15_attr2;
    G7 --> E3_attr4;
    G8 --> E2_attr6;
    G9 --> E9_attr3;
    G10 --> E21_attr6;
    G11 --> E4_attr3;

    %% Condition -> Attribute Connections
    C0 --> E1_attr2;
    C1 --> E0_attr5;
    C2 --> E2_attr0;
    C3 --> E17_attr5;
    C4 --> E20_attr4;
    C5 --> E3_attr3;
    C6 --> E4_attr0;
    C7 --> E1;
    C8 --> E9_attr1;
    C9 --> E8_attr0;
    C10 --> E18_attr3;
    C11 --> E23_attr2;
    C12 --> E17_attr0;

    %% Decision Variable -> Entity Connections
    DV0 --> E2; DV0 --> E1;
    DV1 --> E17; DV1 --> E9;
    DV2 --> E3; DV2 --> E23;
    DV3 --> E18; DV3 --> E2;
    DV4 --> E0;
    DV5 --> E9_attr2;
    DV6 --> E9_attr3;
    DV7 --> E2_attr6;
    DV8 --> E3_attr4;
    DV9 --> E18_attr4;
    DV10 --> E0_attr5;
    DV11 --> E2 & E4 & E18;