graph TD
    %% =============== STYLING ===============
    classDef entity fill:#1f77b4,stroke:#000,color:white,font-weight:bold;
    classDef attribute fill:#ffffff,stroke:#333,stroke-width:1px,color:#333;
    classDef relation fill:#ff8c00,stroke:#000,color:white,font-weight:bold;
    classDef goal fill:#2ca02c,stroke:#000,color:white,font-weight:bold;
    classDef condition fill:#d62728,stroke:#000,color:white,font-weight:bold;
    classDef decisionvar fill:#9467bd,stroke:#000,color:white,font-weight:bold;

    %% =============== ENTITIES ===============
    E0[Project]:::entity
    E1[Team]:::entity
    E2[Worker]:::entity
    E3[Feature]:::entity
    E4[Skill]:::entity
    E5[Role]:::entity
    E6[ProductOwner]:::entity
    E7[ScrumMaster]:::entity
    E8[ProductBacklog]:::entity
    E9[Sprint]:::entity
    E10[SprintPlanning]:::entity
    E11[DailyScrum]:::entity
    E12[SprintReview]:::entity
    E13[SprintRetrospective]:::entity
    E14[SprintBacklog]:::entity
    E15[SprintGoal]:::entity
    E16[Epic]:::entity
    E17[UserStory]:::entity
    E18[Task]:::entity
    E19[DevelopmentSnapshot]:::entity
    E20[Blocker]:::entity
    E21[Stakeholder]:::entity
    E22[Velocity]:::entity
    E23[ReleasePlan]:::entity
    E24[Roadmap]:::entity
    E25[ScrumBoard]:::entity
    E26[FeatureDocumentation]:::entity

    %% =============== ATTRIBUTES ===============
    A0_0[id]:::attribute
    A0_1[name]:::attribute
    A0_2[project_start]:::attribute
    A0_3[project_end]:::attribute
    A0_4[description]:::attribute
    A0_5[budget]:::attribute
    A0_6[status]:::attribute
    A0_7[target_audience]:::attribute
    A0_8[priority]:::attribute

    A1_0[id]:::attribute
    A1_1[name]:::attribute
    A1_2[team_size]:::attribute
    A1_3[team_start]:::attribute
    A1_4[team_status]:::attribute
    A1_5[location]:::attribute
    A1_6[team_type]:::attribute

    A2_0[id]:::attribute
    A2_1[name]:::attribute
    A2_2[first_name]:::attribute
    A2_3[email]:::attribute
    A2_4[start_date]:::attribute
    A2_5[status]:::attribute
    A2_6[availability]:::attribute

    A3_0[id]:::attribute
    A3_1[title]:::attribute
    A3_2[description]:::attribute
    A3_3[status]:::attribute
    A3_4[priority]:::attribute
    A3_5[estimated_effort]:::attribute

    A4_0[id]:::attribute
    A4_1[label]:::attribute
    A4_2[description]:::attribute
    A4_3[level]:::attribute
    A4_4[certified]:::attribute
    A4_5[category]:::attribute

    A5_0[id]:::attribute
    A5_1[role_name]:::attribute
    A5_2[description]:::attribute
    A5_3[area_of_responsibility]:::attribute

    A6_0[id]:::attribute
    A6_1[name]:::attribute
    A6_2[email]:::attribute
    A6_3[availability]:::attribute

    A7_0[id]:::attribute
    A7_1[name]:::attribute
    A7_2[email]:::attribute
    A7_3[experience]:::attribute

    A8_0[id]:::attribute
    A8_1[created_on]:::attribute
    A8_2[last_updated]:::attribute
    A8_3[number_of_entries]:::attribute
    A8_4[status]:::attribute

    A9_0[id]:::attribute
    A9_1[sprint_number]:::attribute
    A9_2[start_date]:::attribute
    A9_3[end_date]:::attribute
    A9_4[status]:::attribute
    A9_5[achievement_of_goal]:::attribute

    A10_0[id]:::attribute
    A10_1[date]:::attribute
    A10_2[duration_(min)]:::attribute
    A10_3[moderation]:::attribute
    A10_4[outcome_documentation]:::attribute

    A11_0[id]:::attribute
    A11_1[date]:::attribute
    A11_2[time]:::attribute
    A11_3[duration]:::attribute
    A11_4[moderation]:::attribute

    A12_0[id]:::attribute
    A12_1[date]:::attribute
    A12_2[duration]:::attribute
    A12_3[feedback_documentation]:::attribute
    A12_4[attendees_count]:::attribute

    A13_0[id]:::attribute
    A13_1[date]:::attribute
    A13_2[duration]:::attribute
    A13_3[improvement_actions]:::attribute
    A13_4[team_satisfaction]:::attribute
    A13_5[moderation]:::attribute

    A14_0[id]:::attribute
    A14_1[number_of_tasks]:::attribute
    A14_2[last_updated]:::attribute
    A14_3[status]:::attribute
    A14_4[total_effort]:::attribute

    A15_0[id]:::attribute
    A15_1[objective_description]:::attribute
    A15_2[achievement_status]:::attribute
    A15_3[benefit]:::attribute

    A16_0[id]:::attribute
    A16_1[title]:::attribute
    A16_2[description]:::attribute
    A16_3[priority]:::attribute
    A16_4[status]:::attribute
    A16_5[estimated_effort]:::attribute

    A17_0[id]:::attribute
    A17_1[title]:::attribute
    A17_2[description]:::attribute
    A17_3[acceptance_criteria]:::attribute
    A17_4[priority]:::attribute
    A17_5[story_points]:::attribute
    A17_6[status]:::attribute

    A18_0[id]:::attribute
    A18_1[title]:::attribute
    A18_2[description]:::attribute
    A18_3[status]:::attribute
    A18_4[effort]:::attribute
    A18_5[type]:::attribute

    A19_0[id]:::attribute
    A19_1[version_number]:::attribute
    A19_2[creation_date]:::attribute
    A19_3[test_status]:::attribute
    A19_4[deployment_target]:::attribute
    A19_5[documentation]:::attribute

    A20_0[id]:::attribute
    A20_1[title]:::attribute
    A20_2[description]:::attribute
    A20_3[severity]:::attribute
    A20_4[status]:::attribute
    A20_5[detected_on]:::attribute
    A20_6[resolved_on]:::attribute

    A21_0[id]:::attribute
    A21_1[name]:::attribute
    A21_2[organization]:::attribute
    A21_3[role]:::attribute
    A21_4[email]:::attribute
    A21_5[area_of_interest]:::attribute
    A21_6[influence_level]:::attribute
    A21_7[relevance_to_feature]:::attribute

    A22_0[id]:::attribute
    A22_1[number_of_sprints_used]:::attribute
    A22_2[avg._story_points]:::attribute
    A22_3[max_velocity]:::attribute
    A22_4[min_velocity]:::attribute
    A22_5[trend]:::attribute

    A23_0[id]:::attribute
    A23_1[version]:::attribute
    A23_2[planned_date]:::attribute
    A23_3[included_features]:::attribute
    A23_4[status]:::attribute

    A24_0[id]:::attribute
    A24_1[start_date]:::attribute
    A24_2[end_date]:::attribute
    A24_3[milestones]:::attribute
    A24_4[objectives]:::attribute
    A24_5[versions]:::attribute

    A25_0[id]:::attribute
    A25_1[board_type]:::attribute
    A25_2[columns_(todo/done...)]:::attribute
    A25_3[number_of_cards]:::attribute
    A25_4[last_updated]:::attribute

    A26_0[id]:::attribute
    A26_1[title]:::attribute
    A26_2[description]:::attribute
    A26_3[creation_date]:::attribute
    A26_4[change_log]:::attribute
    A26_5[linked_requirements]:::attribute
    A26_6[author]:::attribute

    %% =============== RELATIONSHIPS ===============
    R1[is_assigned_to_project]:::relation
    R2[belongs_to_team]:::relation
    R3[has_skill]:::relation
    R4[takes_on_role]:::relation
    R5[manages_backlog]:::relation
    R6[is_supported_by]:::relation
    R7[contains_feature]:::relation
    R8[contains_epic]:::relation
    R9[contains_user_story]:::relation
    R10[consists_of_tasks]:::relation
    R11[is_in_sprint_backlog]:::relation
    R12[belongs_to_sprint]:::relation
    R13[pursues_goal]:::relation
    R14[contains_tasks]:::relation
    R15[documents_feature]:::relation
    R16[is_blocked_by]:::relation
    R17[participates_in]:::relation
    R18[moderates_retrospective]:::relation
    R19[refers_to_team]:::relation
    R20[plans_release]:::relation
    R21[is_part_of_roadmap]:::relation
    R22[generates_snapshot]:::relation

    %% =============== GOALS ===============
    G0[maximize_project_budget]:::goal
    G1[maximize_team_size]:::goal
    G2[maximize_worker_availability]:::goal
    G3[minimize_project_duration]:::goal
    G4[maximize_feature_priority]:::goal
    G5[maximize_story_points]:::goal
    G6[minimize_task_effort]:::goal
    G7[maximize_sprint_achievement]:::goal
    G8[maximize_velocity_trend]:::goal
    G9[minimize_blocker_severity]:::goal
    G10[maximize_stakeholder_influence]:::goal
    G11[maximize_documentation_coverage]:::goal
    G12[minimize_sprint_duration]:::goal
    G13[maximize_release_inclusion]:::goal
    G14[maximize_epic_effort_estimate]:::goal

    %% =============== CONDITIONS ===============
    C0[require_project_status]:::condition
    C1[require_team_location]:::condition
    C2[require_worker_status]:::condition
    C3[require_feature_status]:::condition
    C4[require_task_status]:::condition
    C5[require_role_certification]:::condition
    C6[require_user_story_status]:::condition
    C7[require_sprint_status]:::condition
    C8[require_blocker_status]:::condition
    C9[require_velocity_min_value]:::condition
    C10[require_stakeholder_relevance]:::condition
    C11[require_skill_certified]:::condition
    C12[require_documentation_author]:::condition
    C13[require_scumb_board_type]:::condition
    C14[require_development_test_status]:::condition

    %% =============== DECISION VARIABLES ===============
    DV0[project_priority_weight]:::decisionvar
    DV1[team_capacity_utilization]:::decisionvar
    DV2[task_assignment_binary]:::decisionvar
    DV3[sprint_inclusion_flag]:::decisionvar
    DV4[feature_release_flag]:::decisionvar
    DV5[worker_availability_hours]:::decisionvar
    DV6[story_point_estimate]:::decisionvar
    DV7[effort_allocation_per_task]:::decisionvar
    DV8[blocker_resolution_time]:::decisionvar
    DV9[documentation_completeness]:::decisionvar
    DV10[sprint_goal_achievement_score]:::decisionvar
    DV11[velocity_prediction]:::decisionvar
    DV12[release_planned_date_deviation]:::decisionvar
    DV13[retrospective_improvement_count]:::decisionvar
    DV14[scrum_board_column_index]:::decisionvar

    %% =============== ENTITY TO ATTRIBUTE CONNECTIONS ===============
    E0 --> A0_0 & A0_1 & A0_2 & A0_3 & A0_4 & A0_5 & A0_6 & A0_7 & A0_8
    E1 --> A1_0 & A1_1 & A1_2 & A1_3 & A1_4 & A1_5 & A1_6
    E2 --> A2_0 & A2_1 & A2_2 & A2_3 & A2_4 & A2_5 & A2_6
    E3 --> A3_0 & A3_1 & A3_2 & A3_3 & A3_4 & A3_5
    E4 --> A4_0 & A4_1 & A4_2 & A4_3 & A4_4 & A4_5
    E5 --> A5_0 & A5_1 & A5_2 & A5_3
    E6 --> A6_0 & A6_1 & A6_2 & A6_3
    E7 --> A7_0 & A7_1 & A7_2 & A7_3
    E8 --> A8_0 & A8_1 & A8_2 & A8_3 & A8_4
    E9 --> A9_0 & A9_1 & A9_2 & A9_3 & A9_4 & A9_5
    E10 --> A10_0 & A10_1 & A10_2 & A10_3 & A10_4
    E11 --> A11_0 & A11_1 & A11_2 & A11_3 & A11_4
    E12 --> A12_0 & A12_1 & A12_2 & A12_3 & A12_4
    E13 --> A13_0 & A13_1 & A13_2 & A13_3 & A13_4 & A13_5
    E14 --> A14_0 & A14_1 & A14_2 & A14_3 & A14_4
    E15 --> A15_0 & A15_1 & A15_2 & A15_3
    E16 --> A16_0 & A16_1 & A16_2 & A16_3 & A16_4 & A16_5
    E17 --> A17_0 & A17_1 & A17_2 & A17_3 & A17_4 & A17_5 & A17_6
    E18 --> A18_0 & A18_1 & A18_2 & A18_3 & A18_4 & A18_5
    E19 --> A19_0 & A19_1 & A19_2 & A19_3 & A19_4 & A19_5
    E20 --> A20_0 & A20_1 & A20_2 & A20_3 & A20_4 & A20_5 & A20_6
    E21 --> A21_0 & A21_1 & A21_2 & A21_3 & A21_4 & A21_5 & A21_6 & A21_7
    E22 --> A22_0 & A22_1 & A22_2 & A22_3 & A22_4 & A22_5
    E23 --> A23_0 & A23_1 & A23_2 & A23_3 & A23_4
    E24 --> A24_0 & A24_1 & A24_2 & A24_3 & A24_4 & A24_5
    E25 --> A25_0 & A25_1 & A25_2 & A25_3 & A25_4
    E26 --> A26_0 & A26_1 & A26_2 & A26_3 & A26_4 & A26_5 & A26_6

    %% =============== RELATIONSHIPS BETWEEN ENTITIES ===============
    R1 --> E1 & E0
    R2 --> E2 & E1
    R3 --> E2 & E4
    R4 --> E2 & E5
    R5 --> E6 & E8
    R6 --> E1 & E7
    R7 --> E8 & E3
    R8 --> E8 & E16
    R9 --> E16 & E17
    R10 --> E17 & E18
    R11 --> E17 & E14
    R12 --> E14 & E9
    R13 --> E9 & E15
    R14 --> E25 & E18
    R15 --> E26 & E3
    R16 --> E18 & E20
    R17 --> E21 & E12
    R18 --> E7 & E13
    R19 --> E22 & E1
    R20 --> E23 & E3
    R21 --> E23 & E24
    R22 --> E9 & E19

    %% =============== GOALS TO ENTITY/ATTRIBUTE ===============
    G0 --> A0_5 & E0
    G1 --> A1_2 & E1
    G2 --> A2_6 & E2
    G3 --> A0_2 & A0_3 & E0
    G4 --> A3_4 & E3
    G5 --> A17_5 & E17
    G6 --> A18_4 & E18
    G7 --> A9_5 & E9
    G8 --> A22_5 & E22
    G9 --> A20_3 & E20
    G10 --> A21_6 & E21
    G11 --> A26_5 & E26
    G12 --> A9_2 & A9_3 & E9
    G13 --> A23_3 & E23
    G14 --> A16_5 & E16

    %% =============== CONDITIONS TO ENTITY/ATTRIBUTE ===============
    C0 --> A0_6 & E0
    C1 --> A1_5 & E1
    C2 --> A2_5 & E2
    C3 --> A3_3 & E3
    C4 --> A18_3 & E18
    C5 --> A5_2 & E5
    C6 --> A17_6 & E17
    C7 --> A9_4 & E9
    C8 --> A20_4 & A20_6 & E20
    C9 --> A22_4 & E22
    C10 --> A21_7 & E21
    C11 --> A4_4 & E4
    C12 --> A26_6 & E26
    C13 --> A25_1 & E25
    C14 --> A19_3 & E19

    %% =============== DECISION VARIABLES TO ENTITIES ===============
    DV0 --> E0
    DV1 --> E1
    DV2 --> E2 & E18
    DV3 --> E17
    DV4 --> E3 & E23
    DV5 --> E2
    DV6 --> E17
    DV7 --> E18
    DV8 --> E20
    DV9 --> E26
    DV10 --> E15
    DV11 --> E22
    DV12 --> E23
    DV13 --> E13
    DV14 --> E25 & E18

    %% =============== OPTIONAL LAYOUT HINTS (for clarity) ===============
    direction TB