Entities:
Entity ID,Entity Name
1,Customer
2,Order
3,Product

Attributes:
Attribute ID,Entity ID,Attribute Name
101,1,Customer Name
102,1,Customer Address
103,2,Order Date
104,2,Total Amount
105,3,Product Name
106,3,Price

Relations:
Relation ID,Entity ID 1,Entity ID 2,Relation Type
201,1,2,Places
202,2,3,Contains

Goals:
Goal ID,Entity ID or Attribute ID,Goal Description
301,1,Increase Customer Loyalty
302,104,Maximize Revenue

Conditions:
Condition ID,Entity ID or Attribute ID,Condition Description
401,1,Customer is VIP
402,103,Order Date is Recent

DecisionVariables:
DecisionVariable ID,Entity ID,DecisionVariable Description
501,1,Marketing Campaign
502,2,Order Fulfillment Strategy