graph TD
    %% Entities
    classDef entity fill:#87CEEB,stroke:#333,stroke-width:2px;
    classDef attribute fill:#FFFFFF,stroke:#333,stroke-width:2px;
    classDef relation fill:#FFA07A,stroke:#333,stroke-width:2px;
    classDef goal fill:#C6F4D6,stroke:#333,stroke-width:2px;
    classDef condition fill:#FFC0CB,stroke:#333,stroke-width:2px;
    classDef decisionVariable fill:#C7B8EA,stroke:#333,stroke-width:2px;

    %% Entities
    E0[Project]:::entity
    E1[Team]:::entity
    E2[Worker]:::entity
    E3[Feature]:::entity
    E4[Skill]:::entity
    E5[Role]:::entity
    E6[ProductOwner]:::entity
    E7[ScrumMaster]:::entity
    E8[ProductBacklog]:::entity
    E9[Sprint]:::entity
    E10[SprintPlanning]:::entity
    E11[DailyScrum]:::entity
    E12[SprintReview]:::entity
    E13[SprintRetrospective]:::entity
    E14[SprintBacklog]:::entity
    E15[SprintGoal]:::entity
    E16[Epic]:::entity
    E17[UserStory]:::entity
    E18[Task]:::entity
    E19[DevelopmentSnapshot]:::entity
    E20[Blocker]:::entity
    E21[Stakeholder]:::entity
    E22[Velocity]:::entity
    E23[ReleasePlan]:::entity
    E24[Roadmap]:::entity
    E25[ScrumBoard]:::entity
    E26[FeatureDocumentation]:::entity

    %% Attributes
    id_Project:::attribute --> E0
    name_Project:::attribute --> E0
    project_start:::attribute --> E0
    project_end:::attribute --> E0
    budget:::attribute --> E0
    id_Team:::attribute --> E1
    name_Team:::attribute --> E1
    team_size:::attribute --> E1
    id_Worker:::attribute --> E2
    name_Worker:::attribute --> E2
    email_Worker:::attribute --> E2
    id_Feature:::attribute --> E3
    title_Feature:::attribute --> E3
    priority_Feature:::attribute --> E3

    %% Relations
    R1[is_assigned_to_project]:::relation --> E0
    R1 --> E1
    R2[belongs_to_team]:::relation --> E1
    R2 --> E2
    R3[has_skill]:::relation --> E2
    R3 --> E4
    R4[takes_on_role]:::relation --> E2
    R4 --> E5
    R5[manages_backlog]:::relation --> E6
    R5 --> E8
    R6[is_supported_by]:::relation --> E1
    R6 --> E7

    %% Goals
    G0[maximize_project_budget]:::goal --> budget:::attribute
    G0 --> E0
    G1[minimize_project_duration]:::goal --> project_end:::attribute
    G1 --> E0
    G2[maximize_team_size]:::goal --> team_size:::attribute
    G2 --> E1
    G3[maximize_feature_priority]:::goal --> priority_Feature:::attribute
    G3 --> E3

    %% Conditions
    C0[project_status_must_be_active]:::condition --> E0
    C0 --> status_Project:::attribute
    C1[team_status_must_be_active]:::condition --> E1
    C1 --> team_status:::attribute
    C2[feature_status_must_be_in_progress]:::condition --> E3
    C2 --> status_Feature:::attribute

    %% Decision Variables
    D0[project_start_date]:::decisionVariable --> project_start:::attribute
    D0 --> E0
    D1[team_size]:::decisionVariable --> team_size:::attribute
    D1 --> E1
    D2[feature_priority]:::decisionVariable --> priority_Feature:::attribute
    D2 --> E3