graph TD
    %% =============== STYLING ===============
    classDef entity fill:#1f7bff,stroke:#0050d5,color:white,font-weight:bold,font-size:14px;
    classDef attribute fill:#ffffff,stroke:#333,stroke-width:1px,color:#333,font-size:12px;
    classDef relation fill:#ff8c00,stroke:#cc6600,color:white,font-weight:bold,font-size:12px;
    classDef goal fill:#00b300,stroke:#007a00,color:white,font-size:12px;
    classDef condition fill:#e60000,stroke:#b30000,color:white,font-size:12px;
    classDef decisionVar fill:#9933cc,stroke:#6600cc,color:white,font-size:12px;

    %% =============== ENTITIES (E0–E26) ===============
    E0[Project]:::entity
    E1[Team]:::entity
    E2[Worker]:::entity
    E3[Feature]:::entity
    E4[Skill]:::entity
    E5[Role]:::entity
    E6[ProductOwner]:::entity
    E7[ScrumMaster]:::entity
    E8[ProductBacklog]:::entity
    E9[Sprint]:::entity
    E10[SprintPlanning]:::entity
    E11[DailyScrum]:::entity
    E12[SprintReview]:::entity
    E13[SprintRetrospective]:::entity
    E14[SprintBacklog]:::entity
    E15[SprintGoal]:::entity
    E16[Epic]:::entity
    E17[UserStory]:::entity
    E18[Task]:::entity
    E19[DevelopmentSnapshot]:::entity
    E20[Blocker]:::entity
    E21[Stakeholder]:::entity
    E22[Velocity]:::entity
    E23[ReleasePlan]:::entity
    E24[Roadmap]:::entity
    E25[ScrumBoard]:::entity
    E26[FeatureDocumentation]:::entity

    %% =============== ATTRIBUTES (connected to entities) ===============
    A0a(id):::attribute
    A0b(name):::attribute
    A0c(project_start):::attribute
    A0d(project_end):::attribute
    A0e(description):::attribute
    A0f(budget):::attribute
    A0g(status):::attribute
    A0h(target_audience):::attribute
    A0i(priority):::attribute
    E0 --> A0a & A0b & A0c & A0d & A0e & A0f & A0g & A0h & A0i

    A1a(id):::attribute
    A1b(name):::attribute
    A1c(team_size):::attribute
    A1d(team_start):::attribute
    A1e(team_status):::attribute
    A1f(location):::attribute
    A1g(team_type):::attribute
    E1 --> A1a & A1b & A1c & A1d & A1e & A1f & A1g

    A2a(id):::attribute
    A2b(name):::attribute
    A2c(first_name):::attribute
    A2d(email):::attribute
    A2e(start_date):::attribute
    A2f(status):::attribute
    A2g(availability):::attribute
    E2 --> A2a & A2b & A2c & A2d & A2e & A2f & A2g

    A3a(id):::attribute
    A3b(title):::attribute
    A3c(description):::attribute
    A3d(status):::attribute
    A3e(priority):::attribute
    A3f(estimated_effort):::attribute
    E3 --> A3a & A3b & A3c & A3d & A3e & A3f

    A4a(id):::attribute
    A4b(label):::attribute
    A4c(description):::attribute
    A4d(level):::attribute
    A4e(certified):::attribute
    A4f(category):::attribute
    E4 --> A4a & A4b & A4c & A4d & A4e & A4f

    A5a(id):::attribute
    A5b(role_name):::attribute
    A5c(description):::attribute
    A5d(area_of_responsibility):::attribute
    E5 --> A5a & A5b & A5c & A5d

    A6a(id):::attribute
    A6b(name):::attribute
    A6c(email):::attribute
    A6d(availability):::attribute
    E6 --> A6a & A6b & A6c & A6d

    A7a(id):::attribute
    A7b(name):::attribute
    A7c(email):::attribute
    A7d(experience):::attribute
    E7 --> A7a & A7b & A7c & A7d

    A8a(id):::attribute
    A8b(created_on):::attribute
    A8c(last_updated):::attribute
    A8d(number_of_entries):::attribute
    A8e(status):::attribute
    E8 --> A8a & A8b & A8c & A8d & A8e

    A9a(id):::attribute
    A9b(sprint_number):::attribute
    A9c(start_date):::attribute
    A9d(end_date):::attribute
    A9e(status):::attribute
    A9f(achievement_of_goal):::attribute
    E9 --> A9a & A9b & A9c & A9d & A9e & A9f

    A10a(id):::attribute
    A10b(date):::attribute
    A10c(duration_(min)):::attribute
    A10d(moderation):::attribute
    A10e(outcome_documentation):::attribute
    E10 --> A10a & A10b & A10c & A10d & A10e

    A11a(id):::attribute
    A11b(date):::attribute
    A11c(time):::attribute
    A11d(duration):::attribute
    A11e(moderation):::attribute
    E11 --> A11a & A11b & A11c & A11d & A11e

    A12a(id):::attribute
    A12b(date):::attribute
    A12c(duration):::attribute
    A12d(feedback_documentation):::attribute
    A12e(attendees_count):::attribute
    E12 --> A12a & A12b & A12c & A12d & A12e

    A13a(id):::attribute
    A13b(date):::attribute
    A13c(duration):::attribute
    A13d(improvement_actions):::attribute
    A13e(team_satisfaction):::attribute
    A13f(moderation):::attribute
    E13 --> A13a & A13b & A13c & A13d & A13e & A13f

    A14a(id):::attribute
    A14b(number_of_tasks):::attribute
    A14c(last_updated):::attribute
    A14d(status):::attribute
    A14e(total_effort):::attribute
    E14 --> A14a & A14b & A14c & A14d & A14e

    A15a(id):::attribute
    A15b(objective_description):::attribute
    A15c(achievement_status):::attribute
    A15d(benefit):::attribute
    E15 --> A15a & A15b & A15c & A15d

    A16a(id):::attribute
    A16b(title):::attribute
    A16c(description):::attribute
    A16d(priority):::attribute
    A16e(status):::attribute
    A16f(estimated_effort):::attribute
    E16 --> A16a & A16b & A16c & A16d & A16e & A16f

    A17a(id):::attribute
    A17b(title):::attribute
    A17c(description):::attribute
    A17d(acceptance_criteria):::attribute
    A17e(priority):::attribute
    A17f(story_points):::attribute
    A17g(status):::attribute
    E17 --> A17a & A17b & A17c & A17d & A17e & A17f & A17g

    A18a(id):::attribute
    A18b(title):::attribute
    A18c(description):::attribute
    A18d(status):::attribute
    A18e(effort):::attribute
    A18f(type):::attribute
    E18 --> A18a & A18b & A18c & A18d & A18e & A18f

    A19a(id):::attribute
    A19b(version_number):::attribute
    A19c(creation_date):::attribute
    A19d(test_status):::attribute
    A19e(deployment_target):::attribute
    A19f(documentation):::attribute
    E19 --> A19a & A19b & A19c & A19d & A19e & A19f

    A20a(id):::attribute
    A20b(title):::attribute
    A20c(description):::attribute
    A20d(severity):::attribute
    A20e(status):::attribute
    A20f(detected_on):::attribute
    A20g(resolved_on):::attribute
    E20 --> A20a & A20b & A20c & A20d & A20e & A20f & A20g

    A21a(id):::attribute
    A21b(name):::attribute
    A21c(organization):::attribute
    A21d(role):::attribute
    A21e(email):::attribute
    A21f(area_of_interest):::attribute
    A21g(influence_level):::attribute
    A21h(relevance_to_feature):::attribute
    E21 --> A21a & A21b & A21c & A21d & A21e & A21f & A21g & A21h

    A22a(id):::attribute
    A22b(number_of_sprints_used):::attribute
    A22c(avg._story_points):::attribute
    A22d(max_velocity):::attribute
    A22e(min_velocity):::attribute
    A22f(trend):::attribute
    E22 --> A22a & A22b & A22c & A22d & A22e & A22f

    A23a(id):::attribute
    A23b(version):::attribute
    A23c(planned_date):::attribute
    A23d(included_features):::attribute
    A23e(status):::attribute
    E23 --> A23a & A23b & A23c & A23d & A23e

    A24a(id):::attribute
    A24b(start_date):::attribute
    A24c(end_date):::attribute
    A24d(milestones):::attribute
    A24e(objectives):::attribute
    A24f(versions):::attribute
    E24 --> A24a & A24b & A24c & A24d & A24e & A24f

    A25a(id):::attribute
    A25b(board_type):::attribute
    A25c(columns_(todo/done...)):::attribute
    A25d(number_of_cards):::attribute
    A25e(last_updated):::attribute
    E25 --> A25a & A25b & A25c & A25d & A25e

    A26a(id):::attribute
    A26b(title):::attribute
    A26c(description):::attribute
    A26d(creation_date):::attribute
    A26e(change_log):::attribute
    A26f(linked_requirements):::attribute
    A26g(author):::attribute
    E26 --> A26a & A26b & A26c & A26d & A26e & A26f & A26g

    %% =============== RELATIONS (R1–R22) ===============
    R1[is_assigned_to_project]:::relation
    R2[belongs_to_team]:::relation
    R3[has_skill]:::relation
    R4[takes_on_role]:::relation
    R5[manages_backlog]:::relation
    R6[is_supported_by]:::relation
    R7[contains_feature]:::relation
    R8[contains_epic]:::relation
    R9[contains_user_story]:::relation
    R10[consists_of_tasks]:::relation
    R11[is_in_sprint_backlog]:::relation
    R12[belongs_to_sprint]:::relation
    R13[pursues_goal]:::relation
    R14[contains_tasks]:::relation
    R15[documents_feature]:::relation
    R16[is_blocked_by]:::relation
    R17[participates_in]:::relation
    R18[moderates_retrospective]:::relation
    R19[refers_to_team]:::relation
    R20[plans_release]:::relation
    R21[is_part_of_roadmap]:::relation
    R22[generates_snapshot]:::relation

    E1 --> R1 --> E0
    E2 --> R2 --> E1
    E2 --> R3 --> E4
    E2 --> R4 --> E5
    E6 --> R5 --> E8
    E1 --> R6 --> E7
    E8 --> R7 --> E3
    E8 --> R8 --> E16
    E16 --> R9 --> E17
    E17 --> R10 --> E18
    E17 --> R11 --> E14
    E14 --> R12 --> E9
    E9 --> R13 --> E15
    E25 --> R14 --> E18
    E26 --> R15 --> E3
    E18 --> R16 --> E20
    E21 --> R17 --> E12
    E7 --> R18 --> E13
    E22 --> R19 --> E1
    E23 --> R20 --> E3
    E23 --> R21 --> E24
    E9 --> R22 --> E19

    %% =============== GOALS (G0–G13) ===============
    G0[maximize_team_productivity]:::goal
    G1[minimize_sprint_blockers]:::goal
    G2[maximize_worker_utilization]:::goal
    G3[maximize_backlog_clarity]:::goal
    G4[minimize_sprint_goal_failures]:::goal
    G5[maximize_stakeholder_satisfaction]:::goal
    G6[maximize_documentation_coverage]:::goal
    G7[minimize_technical_debt_tasks]:::goal
    G8[maximize_sprint_completion_rate]:::goal
    G9[minimize_requirement_ambiguity]:::goal
    G10[maximize_team_stability]:::goal
    G11[minimize_sprint_duration_waste]:::goal
    G12[maximize_skill_coverage]:::goal
    G13[minimize_context_switching]:::goal

    G0 --> A22c  %% avg._story_points
    G1 --> A20e  %% status (blocker)
    G2 --> A2g   %% availability (worker)
    G3 --> A17d  %% acceptance_criteria
    G4 --> A9f   %% achievement_of_goal
    G5 --> A21g  %% influence_level
    G6 --> A26f  %% linked_requirements
    G7 --> A18f  %% type (task)
    G8 --> A14d  %% status (sprint backlog)
    G9 --> A17e & A17f  %% priority, story_points
    G10 --> A2e  %% start_date
    G11 --> A23c & A9d  %% planned_date, end_date
    G12 --> A4d  %% level (skill)
    G13 --> A18e  %% effort (task)

    %% =============== CONDITIONS (C0–C12) ===============
    C0[require_product_owner_availability]:::condition
    C1[require_sprint_goal_defined]:::condition
    C2[require_defined_done]:::condition
    C3[limit_team_size]:::condition
    C4[require_backlog_refinement]:::condition
    C5[require_unique_role_assignment]:::condition
    C6[require_sprint_review_attendance]:::condition
    C7[require_velocity_stability]:::condition
    C8[require_task_effort_estimation]:::condition
    C9[require_feature_priority]:::condition
    C10[require_epic_decomposition]:::condition
    C11[require_documented_blockers]:::condition
    C12[require_sprint_snapshot]:::condition

    C0 --> A6d   %% availability (PO)
    C1 --> A15b  %% objective_description
    C2 --> A18d  %% status (task)
    C3 --> A1c   %% team_size
    C4 --> A8d   %% number_of_entries (backlog)
    C5 --> A5b   %% role_name
    C6 --> A12e  %% attendees_count
    C7 --> A22f  %% trend (velocity)
    C8 --> A18e  %% effort (task)
    C9 --> A3e   %% priority (feature)
    C10 --> A16e  %% status (epic)
    C11 --> A20c  %% description (blocker)
    C12 --> A19a  %% version_number (snapshot)

    %% =============== DECISION VARIABLES (DV0–DV14) ===============
    DV0[worker_assignment]:::decisionVar
    DV1[task_priority]:::decisionVar
    DV2[sprint_length]:::decisionVar
    DV3[story_points]:::decisionVar
    DV4[team_size]:::decisionVar
    DV5[refinement_effort_hours]:::decisionVar
    DV6[task_effort_hours]:::decisionVar
    DV7[feature_release_version]:::decisionVar
    DV8[worker_skill_level]:::decisionVar
    DV9[scrum_board_columns]:::decisionVar
    DV10[velocity_forecast]:::decisionVar
    DV11[stakeholder_influence_weight]:::decisionVar
    DV12[documentation_completeness]:::decisionVar
    DV13[blocker_severity_level]:::decisionVar
    DV14[retrospective_frequency]:::decisionVar

    DV0 --> E2 & E18
    DV1 --> A18e
    DV2 --> A9b & A9c & A9d
    DV3 --> A17f
    DV4 --> A1c
    DV5 --> E8
    DV6 --> A18e
    DV7 --> A23b
    DV8 --> A4d
    DV9 --> A25c
    DV10 --> A22c
    DV11 --> A21g
    DV12 --> A26f
    DV13 --> A20d
    DV14 --> E13

    %% =============== END OF GRAPH ===============