name: Extract Chat Files

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  extract-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies (if any)
      run: |
        python -m pip install --upgrade pip

    - name: Run chat-to-files extractor
      run: |
        python tools/json_to_files.py

    - name: Run keyword analysis
      run: python tools/json_to_files.py

    - name: Commit and push generated files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add large-language-models/local-llm/**/*.csv
        git add large-language-models/local-llm/**/*.tex
        git add large-language-models/local-llm/**/*.mmd
        git commit -m "Auto-generate files from chat.json"
        git push

