graph TD
    A[Project] --> B[Team]
    A --> C[Task]
    A --> D[Sprint]
    A --> E[Blocker]
    A --> F[Stakeholder]
    A --> G[Feature]
    A --> H[SprintGoal]
    A --> I[SprintBacklog]
    A --> J[DevelopmentSnapshot]
    A --> K[SprintRetrospective]
    B --> L[TeamSize]
    C --> M[Effort]
    D --> N[Duration]
    E --> O[Severity]
    F --> P[Influence]
    G --> Q[Priority]
    H --> R[Benefit]
    I --> S[NumberTasks]
    I --> T[BacklogEffort]
    J --> U[Quality]
    K --> V[Satisfaction]